CREATE TABLE IF NOT EXISTS EB_USER (
    USER_ID     VARCHAR(50) PRIMARY KEY,
    USER_NAME   VARCHAR(100),
    BRANCH_ID   VARCHAR(20),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EB_EVENT (
    EVENT_ID      VARCHAR(50) PRIMARY KEY,
    USER_ID       VARCHAR(50) NOT NULL,
    EVENT_TYPE    VARCHAR(30) NOT NULL,
    EVENT_STATUS  VARCHAR(20) NOT NULL,
    RETRY_COUNT   INT DEFAULT 0,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SENT_AT       TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_EB_EVENT_STATUS ON EB_EVENT (EVENT_STATUS, CREATED_AT);

-- 화면 19410 시스템 거래 현황
CREATE TABLE IF NOT EXISTS EB_SYSTEM_TX (
    TX_SEQ_NO      VARCHAR(40) PRIMARY KEY,
    TX_DATE        VARCHAR(10) NOT NULL,
    SCREEN_ID      VARCHAR(20),
    SERVICE_ID     VARCHAR(80),
    GLOBAL_ID      VARCHAR(64),
    REQUEST_AT     TIMESTAMP NOT NULL,
    RESPONSE_AT    TIMESTAMP,
    ELAPSED_SEC    INT,
    INPUT_CONTENT  VARCHAR(1000),
    EMP_NO         VARCHAR(20),
    BRANCH_CODE    VARCHAR(20),
    TERMINAL_IP    VARCHAR(40),
    TX_TYPE        VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS IX_EB_SYSTEM_TX_REQ ON EB_SYSTEM_TX (REQUEST_AT, TX_TYPE);
CREATE INDEX IF NOT EXISTS IX_EB_SYSTEM_TX_SVC ON EB_SYSTEM_TX (SERVICE_ID, SCREEN_ID);
