-- tcf-oc Hello World 샘플 (eb-service schema.sql 패턴)

CREATE TABLE IF NOT EXISTS CP_HELLO_LOG (
    LOG_ID      VARCHAR(50) PRIMARY KEY,
    NAME        VARCHAR(100),
    MESSAGE     VARCHAR(200),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- NEW 용량산정 Wizard 시나리오 (cap-new, 기존 CAP/ENV와 분리)
CREATE TABLE IF NOT EXISTS CAP_NEW_SCENARIO (
    SCENARIO_ID    VARCHAR(50)  NOT NULL PRIMARY KEY,
    PROJECT_ID     VARCHAR(50)  NOT NULL,
    PROJECT_NAME   VARCHAR(200),
    SCENARIO_NAME  VARCHAR(200) NOT NULL,
    TARGET_ENV     VARCHAR(20),
    BASE_DATE      DATE,
    VERSION_NO     VARCHAR(20),
    AUTHOR         VARCHAR(100),
    DESCRIPTION    VARCHAR(500),
    PURPOSE        VARCHAR(30),
    STATUS         VARCHAR(20)  DEFAULT 'DRAFT',
    CURRENT_STEP   INT          DEFAULT 1,
    STEP_PAYLOAD   CLOB,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- NEW 용량산정 시나리오 템플릿 카탈로그 (초기값·메타·seed payload)
CREATE TABLE IF NOT EXISTS CAP_NEW_SCENARIO_TEMPLATE (
    TEMPLATE_CODE     VARCHAR(50)  NOT NULL PRIMARY KEY,
    LABEL             VARCHAR(200) NOT NULL,
    DESCRIPTION       VARCHAR(500),
    PURPOSE           VARCHAR(30),
    TARGET_ENV        VARCHAR(20),
    VM_PROFILE_CODE   VARCHAR(30),
    TOTAL_USERS       INT,
    DESIGN_PEAK_TPS   INT,
    DEPLOYMENT_AP     INT,
    MAX_THREADS       INT,
    POOL_PER_VM       INT,
    SORT_ORDER        INT          DEFAULT 0,
    ENABLED           VARCHAR(1)   DEFAULT 'Y',
    SEED_PAYLOAD      CLOB,
    CREATED_AT        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CAP_NEW_APPROVAL (
    APPROVAL_ID       VARCHAR(50)  NOT NULL PRIMARY KEY,
    SCENARIO_ID       VARCHAR(50)  NOT NULL,
    PROJECT_ID        VARCHAR(50)  NOT NULL,
    SCENARIO_NAME     VARCHAR(200),
    VERSION_NO        VARCHAR(20),
    ACTION            VARCHAR(20)  DEFAULT 'APPROVE',
    APPROVER          VARCHAR(100),
    REVIEWER          VARCHAR(100),
    APPROVAL_NOTE     VARCHAR(500),
    OVERALL_JUDGMENT  VARCHAR(20),
    SNAPSHOT_JSON     CLOB,
    CREATED_AT        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_CAPACITY_ACCOUNT (
    ACCOUNT_NUMBER         VARCHAR(30)  NOT NULL PRIMARY KEY,
    NAME                   VARCHAR(100),
    IDENTIFICATION_NUMBER  VARCHAR(20),
    INTEREST_RATE          DOUBLE,
    LAST_TRANSACTION       TIMESTAMP,
    PASSWORD               VARCHAR(100),
    NET_AMOUNT             DOUBLE,
    ACCOUNT_TYPE           VARCHAR(20),
    STATUS                 VARCHAR(20),
    CURRENCY               VARCHAR(10),
    CREATED_DATE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
