# dev - ztomcat WAR (/sv)
spring:
  application:
    name: nsight-sv-service
  datasource:
    url: jdbc:h2:tcp://127.0.0.1:9092/./nsight_om;MODE=Oracle;DATABASE_TO_UPPER=false
    hikari:
      pool-name: nsight-sv-hikari-dev
  h2:
    console:
      enabled: true

nsight:
  tcf:
    transaction-log-schema-auto-init: true
    transaction-control-datasource:
      url: jdbc:h2:tcp://127.0.0.1:9092/./nsight_om;MODE=Oracle;DATABASE_TO_UPPER=false
    transaction-log-datasource:
      separate: false
      url: jdbc:h2:tcp://127.0.0.1:9092/./nsight_om;MODE=Oracle;DATABASE_TO_UPPER=false
      username: sa
      password:
      driver-class-name: org.h2.Driver
    runtime-monitor-enabled: true
    runtime-slow-sql-threshold-ms: 1000
    runtime:
      business-code: SV
