param([ValidateSet('Contracts','Skills','Simulation','Verifier','All')][string]$Mode='All')
$ErrorActionPreference='Stop';$script:Failures=[System.Collections.Generic.List[string]]::new();$Root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
function Assert-True{param([bool]$Condition,[string]$Message)if(-not $Condition){$script:Failures.Add($Message)}}
function Assert-FileContains{param([string]$Path,[string[]]$Patterns)if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){$script:Failures.Add("Missing file: $Path");return};$content=Get-Content -Raw -Encoding UTF8 $Path;foreach($pattern in $Patterns){if($content -notmatch [regex]::Escape($pattern)){$script:Failures.Add("Missing '$pattern' in $Path")}}}
function Test-Contracts{foreach($r in @('AGENTS.md','README.md','docs/quickstart.md','docs/migration-from-claude.md','agents/analyst.md','agents/builder.md','agents/qa.md')){Assert-True (Test-Path (Join-Path $Root $r) -PathType Leaf) "Missing file: $r"};foreach($role in @('analyst','builder','qa')){$p=Join-Path $Root "agents/$role.md";if(Test-Path $p){$c=Get-Content -Raw -Encoding UTF8 $p;$n=([regex]::Matches($c,'(?m)^## [^#\r\n]+$')).Count;Assert-True ($n -eq 6) "Expected 6 role sections in $p, found $n"}};Assert-FileContains (Join-Path $Root 'README.md') @('Codex','AGENTS.md','SKILL.md','verify-codex-harness.ps1')}
function Test-Skills{Assert-FileContains (Join-Path $Root 'skills/harness/SKILL.md') @('name: harness','description:','spawn_agent','send_message','followup_task','wait_agent');Assert-FileContains (Join-Path $Root 'skills/harness/orchestrator-sample/SKILL.md') @('name:','description:','Analyst','Builder','QA','tcf-harness-world');foreach($r in @('skills/harness/references/agent-design-patterns.md','skills/harness/references/orchestrator-template.md','skills/harness/references/codex-tool-mapping.md')){Assert-True (Test-Path (Join-Path $Root $r) -PathType Leaf) "Missing file: $r"}}
function Test-Simulation{$s=Join-Path $Root 'skills/harness/orchestrator-sample/scripts/run-simulation.ps1';Assert-True (Test-Path $s -PathType Leaf) "Missing file: $s";if(-not(Test-Path $s)){return};$b=Join-Path ([IO.Path]::GetTempPath()) ("tcf-harness-test-"+[guid]::NewGuid());$w=Join-Path $b 'workspace';$r=Join-Path $b 'runs';try{& $s -Workspace $w -RunDirectory $r;& $s -Workspace $w -RunDirectory $r;foreach($n in @('analysis-summary.md','poc-plan.md')){$p=Join-Path $w $n;Assert-True ((Test-Path $p)-and((Get-Item $p).Length -gt 0)) "Missing artifact: $n";if(Test-Path $p){$titles=(Select-String -Path $p -Pattern '^# ' -Encoding UTF8).Count;Assert-True ($titles -eq 1) "Expected one title in $n"}};Assert-FileContains (Join-Path $r 'orchestrator-simulation.log') @('QA PASS')}finally{if(Test-Path $b){Remove-Item $b -Recurse -Force}}}
function Invoke-Verify{param([string]$Tree)$v=Join-Path $Root 'scripts/verify-codex-harness.ps1';if(-not(Test-Path $v)){return 127};& $v -Root $Tree *> $null;return $LASTEXITCODE}
function Test-Verifier{$v=Join-Path $Root 'scripts/verify-codex-harness.ps1';Assert-True (Test-Path $v -PathType Leaf) "Missing file: $v";if(-not(Test-Path $v)){return};Assert-True ((Invoke-Verify $Root)-eq 0) 'Verifier rejected valid tree';$b=Join-Path ([IO.Path]::GetTempPath()) ("tcf-harness-verify-"+[guid]::NewGuid());try{Copy-Item $Root $b -Recurse;Add-Content -Encoding UTF8 (Join-Path $b 'README.md') 'forbidden-runtime-marker: .claude/skills';Assert-True ((Invoke-Verify $b)-ne 0) 'Verifier accepted forbidden runtime marker';Remove-Item (Join-Path $b 'agents/qa.md') -Force;Assert-True ((Invoke-Verify $b)-ne 0) 'Verifier accepted missing QA role'}finally{if(Test-Path $b){Remove-Item $b -Recurse -Force}}}
switch($Mode){'Contracts'{Test-Contracts};'Skills'{Test-Skills};'Simulation'{Test-Simulation};'Verifier'{Test-Verifier};'All'{Test-Contracts;Test-Skills;Test-Simulation;Test-Verifier}}
if($script:Failures.Count){$script:Failures|ForEach-Object{Write-Error $_ -ErrorAction Continue};exit 1};Write-Host "$Mode checks passed.";exit 0
