-- pdmg-infra 로컬 H2 스키마 (Oracle 호환 모드)

DROP VIEW IF EXISTS V_IF_PROPOSAL_TCO;
DROP VIEW IF EXISTS V_IF_EOL_RISK;
DROP VIEW IF EXISTS V_IF_MIGRATION_MAPPING;
DROP VIEW IF EXISTS V_IF_SERVER_GROUP_CAPACITY;
DROP VIEW IF EXISTS V_IF_SERVER_INVENTORY;
DROP TABLE IF EXISTS TB_FW_IMAGE_LOG;
DROP TABLE IF EXISTS TB_IF_COST_PILOT;
DROP TABLE IF EXISTS TB_IF_ASSET_LICENSE_PILOT;
DROP TABLE IF EXISTS TB_IF_LICENSE_PILOT;
DROP TABLE IF EXISTS TB_IF_CAPACITY_PILOT;
DROP TABLE IF EXISTS TB_IF_APP_MAP_PILOT;
DROP TABLE IF EXISTS TB_IF_SECURITY_PROFILE_PILOT;
DROP TABLE IF EXISTS TB_IF_MIGRATION_PLAN_PILOT;
DROP TABLE IF EXISTS TB_IF_MIGRATION_WAVE_PILOT;
DROP TABLE IF EXISTS TB_IF_GATE_RESULT_PILOT;
DROP TABLE IF EXISTS TB_IF_GATE_DEF_PILOT;
DROP TABLE IF EXISTS TB_IF_ASSET_RELATION_PILOT;
DROP TABLE IF EXISTS TB_IF_APP_INTERFACE_PILOT;
DROP TABLE IF EXISTS TB_IF_AVAIL_PROFILE_PILOT;
DROP TABLE IF EXISTS TB_IF_EVIDENCE_FILE_PILOT;
DROP TABLE IF EXISTS TB_IF_CHANGE_LOG_PILOT;
DROP TABLE IF EXISTS TB_IF_NETWORK_EP_PILOT;
DROP TABLE IF EXISTS TB_IF_DB_INSTANCE_PILOT;
DROP TABLE IF EXISTS TB_IF_MW_INSTALL_PILOT;
DROP TABLE IF EXISTS TB_IF_CHECKLIST_RESULT_PILOT;
DROP TABLE IF EXISTS TB_IF_CHECKLIST_ITEM_PILOT;
DROP TABLE IF EXISTS TB_IF_ASSET_ATTR_PILOT;
DROP TABLE IF EXISTS TB_IF_SURVEY_ITEM_PILOT;
DROP TABLE IF EXISTS TB_IF_SURVEY_TMPL_PILOT;
DROP TABLE IF EXISTS TB_IF_APPLICATION_PILOT;
DROP TABLE IF EXISTS TB_IF_SERVER_ASSET_PILOT;
DROP TABLE IF EXISTS TB_IF_SERVER_PILOT;
DROP TABLE IF EXISTS TB_IF_SERVER_GROUP_PILOT;
DROP TABLE IF EXISTS TB_IF_BIZ_SYSTEM_PILOT;
DROP TABLE IF EXISTS TB_IF_PERSON_PILOT;
DROP TABLE IF EXISTS TB_IF_ORG_UNIT_PILOT;
DROP TABLE IF EXISTS TB_IF_CODE_VALUE_PILOT;
DROP TABLE IF EXISTS TB_IF_CODE_SET_PILOT;

CREATE TABLE TB_FW_IMAGE_LOG (
    GUID           VARCHAR(64)   NOT NULL,
    SERVICE_ID     VARCHAR(50),
    SCREEN_ID      VARCHAR(50),
    OPTR_ENO       VARCHAR(20),
    CLIENT_IP      VARCHAR(50),
    REQUEST_TIME   VARCHAR(17),
    RESPONSE_TIME  VARCHAR(17),
    EXCEPTION_TYPE VARCHAR(200),
    EXCEPTION_CODE VARCHAR(50),
    EXCEPTION_MSG  VARCHAR(1000),
    CONSTRAINT TB_FW_IMAGE_LOG_PK PRIMARY KEY (GUID)
);

CREATE TABLE TB_IF_SERVER_PILOT (
    SERVER_ID    VARCHAR(40)   NOT NULL,
    SERVER_NAME  VARCHAR(120)  NOT NULL,
    TECH_ROLE    VARCHAR(40),
    ENV_CD       VARCHAR(20),
    TIER_CD      VARCHAR(20),
    STATUS_CD    VARCHAR(40),
    REMARK       VARCHAR(500),
    REG_USER_ID  VARCHAR(50),
    REG_DTM      VARCHAR(17),
    CHG_USER_ID  VARCHAR(50),
    CHG_DTM      VARCHAR(17),
    CONSTRAINT TB_IF_SERVER_PILOT_PK PRIMARY KEY (SERVER_ID)
);

-- INF-320/330 정규 자산 파일럿 (ifina3100)
CREATE TABLE TB_IF_SERVER_ASSET_PILOT (
    ASSET_ID          VARCHAR(40)   NOT NULL,
    ASSET_NAME        VARCHAR(120)  NOT NULL,
    GROUP_ID          VARCHAR(40),
    SYSTEM_ID         VARCHAR(40),
    ASSET_KIND_CD     VARCHAR(40),
    TECH_ROLE_CD      VARCHAR(40),
    ENV_CD            VARCHAR(20),
    TIER_CD           VARCHAR(20),
    SERVICE_MODEL_CD  VARCHAR(40),
    DEPLOY_MODEL_CD   VARCHAR(40),
    STATUS_CD         VARCHAR(40),
    OS_NAME           VARCHAR(80),
    OS_VERSION        VARCHAR(40),
    OS_EOL_DATE       VARCHAR(10),
    REMARK            VARCHAR(500),
    REG_USER_ID       VARCHAR(50),
    REG_DTM           VARCHAR(17),
    CHG_USER_ID       VARCHAR(50),
    CHG_DTM           VARCHAR(17),
    CONSTRAINT TB_IF_SERVER_ASSET_PILOT_PK PRIMARY KEY (ASSET_ID)
);

CREATE TABLE TB_IF_BIZ_SYSTEM_PILOT (
    SYSTEM_ID    VARCHAR(40)   NOT NULL,
    SYSTEM_NAME  VARCHAR(120)  NOT NULL,
    OWNER_ORG    VARCHAR(80),
    STATUS_CD    VARCHAR(40),
    REMARK       VARCHAR(500),
    REG_USER_ID  VARCHAR(50),
    REG_DTM      VARCHAR(17),
    CHG_USER_ID  VARCHAR(50),
    CHG_DTM      VARCHAR(17),
    CONSTRAINT TB_IF_BIZ_SYSTEM_PILOT_PK PRIMARY KEY (SYSTEM_ID)
);

CREATE TABLE TB_IF_SERVER_GROUP_PILOT (
    GROUP_ID       VARCHAR(40)   NOT NULL,
    GROUP_NAME     VARCHAR(120)  NOT NULL,
    SYSTEM_ID      VARCHAR(40),
    TECH_ROLE_CD   VARCHAR(40),
    ENV_CD         VARCHAR(20),
    TIER_CD        VARCHAR(20),
    STATUS_CD      VARCHAR(40),
    ACTIVE_NODES   INT,
    STANDBY_NODES  INT,
    DR_NODES       INT,
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_SERVER_GROUP_PILOT_PK PRIMARY KEY (GROUP_ID)
);

-- INF-220 Application 파일럿
CREATE TABLE TB_IF_APPLICATION_PILOT (
    APP_ID       VARCHAR(40)   NOT NULL,
    APP_NAME     VARCHAR(120)  NOT NULL,
    SYSTEM_ID    VARCHAR(40)   NOT NULL,
    LANG_CD      VARCHAR(40),
    STATUS_CD    VARCHAR(40),
    REMARK       VARCHAR(500),
    REG_USER_ID  VARCHAR(50),
    REG_DTM      VARCHAR(17),
    CHG_USER_ID  VARCHAR(50),
    CHG_DTM      VARCHAR(17),
    CONSTRAINT TB_IF_APPLICATION_PILOT_PK PRIMARY KEY (APP_ID)
);

-- INF-910 Checklist 마스터/결과 파일럿
CREATE TABLE TB_IF_CHECKLIST_ITEM_PILOT (
    CHECKLIST_ID   VARCHAR(40)   NOT NULL,
    ITEM_NAME      VARCHAR(200)  NOT NULL,
    CATEGORY_KO    VARCHAR(40),
    SEVERITY_CD    VARCHAR(20),
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    SORT_NO        INT,
    REMARK         VARCHAR(500),
    CONSTRAINT TB_IF_CHECKLIST_ITEM_PILOT_PK PRIMARY KEY (CHECKLIST_ID)
);

CREATE TABLE TB_IF_CHECKLIST_RESULT_PILOT (
    CHECKLIST_ID   VARCHAR(40)   NOT NULL,
    TARGET_TYPE    VARCHAR(40)   NOT NULL,
    TARGET_ID      VARCHAR(40)   NOT NULL,
    CHECKED_YN     CHAR(1)       DEFAULT 'N',
    REMARK         VARCHAR(500),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_CHECKLIST_RESULT_PILOT_PK PRIMARY KEY (CHECKLIST_ID, TARGET_TYPE, TARGET_ID)
);

-- INF-410 Middleware 설치 파일럿
CREATE TABLE TB_IF_MW_INSTALL_PILOT (
    MW_ID          VARCHAR(40)   NOT NULL,
    ASSET_ID       VARCHAR(40)   NOT NULL,
    PRODUCT_NAME   VARCHAR(120)  NOT NULL,
    VERSION_NO     VARCHAR(40),
    EOL_DATE       VARCHAR(10),
    STATUS_CD      VARCHAR(40),
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_MW_INSTALL_PILOT_PK PRIMARY KEY (MW_ID)
);

-- INF-420 DB Instance 파일럿
CREATE TABLE TB_IF_DB_INSTANCE_PILOT (
    DB_ID          VARCHAR(40)   NOT NULL,
    DB_NAME        VARCHAR(120)  NOT NULL,
    ENGINE_CD      VARCHAR(40),
    VERSION_NO     VARCHAR(40),
    ASSET_ID       VARCHAR(40),
    SYSTEM_ID      VARCHAR(40),
    EOL_DATE       VARCHAR(10),
    STATUS_CD      VARCHAR(40),
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_DB_INSTANCE_PILOT_PK PRIMARY KEY (DB_ID)
);

-- INF-510 Network Endpoint 파일럿
CREATE TABLE TB_IF_NETWORK_EP_PILOT (
    ENDPOINT_ID      VARCHAR(40)   NOT NULL,
    ASSET_ID         VARCHAR(40)   NOT NULL,
    ENDPOINT_TYPE_CD VARCHAR(20),
    ADDRESS          VARCHAR(80)   NOT NULL,
    PORT_NO          VARCHAR(10),
    PROTOCOL_CD      VARCHAR(20),
    PRIMARY_YN       CHAR(1)       DEFAULT 'N',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_NETWORK_EP_PILOT_PK PRIMARY KEY (ENDPOINT_ID)
);

-- INF-110 분류코드 파일럿
CREATE TABLE TB_IF_CODE_SET_PILOT (
    CODE_SET_ID    VARCHAR(40)   NOT NULL,
    CODE_SET_NAME  VARCHAR(120)  NOT NULL,
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_CODE_SET_PILOT_PK PRIMARY KEY (CODE_SET_ID)
);

CREATE TABLE TB_IF_CODE_VALUE_PILOT (
    CODE_SET_ID    VARCHAR(40)   NOT NULL,
    CODE_VALUE     VARCHAR(40)   NOT NULL,
    NAME_KO        VARCHAR(100)  NOT NULL,
    SORT_ORDER     INT           DEFAULT 0,
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_CODE_VALUE_PILOT_PK PRIMARY KEY (CODE_SET_ID, CODE_VALUE)
);

-- INF-150 조직·담당자 파일럿
CREATE TABLE TB_IF_ORG_UNIT_PILOT (
    ORG_ID         VARCHAR(40)   NOT NULL,
    ORG_NAME       VARCHAR(120)  NOT NULL,
    PARENT_ORG_ID  VARCHAR(40),
    ORG_TYPE_CD    VARCHAR(20),
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_ORG_UNIT_PILOT_PK PRIMARY KEY (ORG_ID)
);

CREATE TABLE TB_IF_PERSON_PILOT (
    PERSON_ID      VARCHAR(40)   NOT NULL,
    PERSON_NAME    VARCHAR(80)   NOT NULL,
    ORG_ID         VARCHAR(40),
    EMAIL          VARCHAR(120),
    ROLE_CD        VARCHAR(20),
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_PERSON_PILOT_PK PRIMARY KEY (PERSON_ID)
);

-- INF-120 조사 템플릿 파일럿
CREATE TABLE TB_IF_SURVEY_TMPL_PILOT (
    TEMPLATE_ID    VARCHAR(40)   NOT NULL,
    TEMPLATE_NAME  VARCHAR(120)  NOT NULL,
    TECH_ROLE_CD   VARCHAR(40),
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_SURVEY_TMPL_PILOT_PK PRIMARY KEY (TEMPLATE_ID)
);

CREATE TABLE TB_IF_SURVEY_ITEM_PILOT (
    TEMPLATE_ID    VARCHAR(40)   NOT NULL,
    ITEM_ID        VARCHAR(40)   NOT NULL,
    ITEM_NAME      VARCHAR(200)  NOT NULL,
    ITEM_TYPE_CD   VARCHAR(40),
    REQUIRED_YN    CHAR(1)       DEFAULT 'N',
    SORT_NO        INT           DEFAULT 0,
    ACTIVE_YN      CHAR(1)       DEFAULT 'Y',
    REMARK         VARCHAR(500),
    REG_USER_ID    VARCHAR(50),
    REG_DTM        VARCHAR(17),
    CHG_USER_ID    VARCHAR(50),
    CHG_DTM        VARCHAR(17),
    CONSTRAINT TB_IF_SURVEY_ITEM_PILOT_PK PRIMARY KEY (TEMPLATE_ID, ITEM_ID)
);

-- INF-330 자산 확장속성 EAV (REQ-F-332)
CREATE TABLE TB_IF_ASSET_ATTR_PILOT (
    ASSET_ID     VARCHAR(40)   NOT NULL,
    ITEM_ID      VARCHAR(40)   NOT NULL,
    ATTR_VALUE   VARCHAR(2000),
    UPDATED_AT   VARCHAR(17),
    CONSTRAINT TB_IF_ASSET_ATTR_PILOT_PK PRIMARY KEY (ASSET_ID, ITEM_ID)
);

-- INF-160 변경이력·증적 파일럿
CREATE TABLE TB_IF_CHANGE_LOG_PILOT (
    LOG_ID           VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    ACTION_CD        VARCHAR(40)   NOT NULL,
    BEFORE_JSON      CLOB,
    AFTER_JSON       CLOB,
    CHANGED_BY       VARCHAR(40),
    CHANGED_AT       VARCHAR(17),
    REMARK           VARCHAR(500),
    CONSTRAINT TB_IF_CHANGE_LOG_PILOT_PK PRIMARY KEY (LOG_ID)
);

CREATE TABLE TB_IF_EVIDENCE_FILE_PILOT (
    EVIDENCE_ID      VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    GATE_ID          VARCHAR(20),
    FILE_NAME        VARCHAR(200),
    FILE_URI         VARCHAR(500),
    URL              VARCHAR(500),
    UPLOADED_BY      VARCHAR(40),
    UPLOADED_AT      VARCHAR(17),
    REMARK           VARCHAR(500),
    CONSTRAINT TB_IF_EVIDENCE_FILE_PILOT_PK PRIMARY KEY (EVIDENCE_ID)
);

-- INF-520 Application Interface 파일럿
CREATE TABLE TB_IF_APP_INTERFACE_PILOT (
    INTERFACE_ID       VARCHAR(40)   NOT NULL,
    FROM_APP_ID        VARCHAR(40)   NOT NULL,
    TO_APP_ID          VARCHAR(40),
    TO_EXTERNAL_NAME   VARCHAR(200),
    PROTOCOL_CD        VARCHAR(40),
    DIRECTION_CD       VARCHAR(20),
    CRITICAL_YN        CHAR(1)       DEFAULT 'N',
    REMARK             VARCHAR(500),
    REG_USER_ID        VARCHAR(50),
    REG_DTM            VARCHAR(17),
    CHG_USER_ID        VARCHAR(50),
    CHG_DTM            VARCHAR(17),
    CONSTRAINT TB_IF_APP_INTERFACE_PILOT_PK PRIMARY KEY (INTERFACE_ID)
);

-- INF-530 의존관계 파일럿
CREATE TABLE TB_IF_ASSET_RELATION_PILOT (
    RELATION_ID      VARCHAR(40)   NOT NULL,
    FROM_TYPE_CD     VARCHAR(20)   NOT NULL,
    FROM_ID          VARCHAR(40)   NOT NULL,
    TO_TYPE_CD       VARCHAR(20)   NOT NULL,
    TO_ID            VARCHAR(40)   NOT NULL,
    RELATION_TYPE_CD VARCHAR(40)   NOT NULL,
    CRITICAL_YN      CHAR(1)       DEFAULT 'N',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_ASSET_RELATION_PILOT_PK PRIMARY KEY (RELATION_ID)
);

-- INF-140/920 Gate 정의·결과 파일럿
CREATE TABLE TB_IF_GATE_DEF_PILOT (
    GATE_ID          VARCHAR(20)   NOT NULL,
    NAME_KO          VARCHAR(120)  NOT NULL,
    DESCRIPTION      VARCHAR(500),
    SORT_NO          INT,
    ACTIVE_YN        CHAR(1)       DEFAULT 'Y',
    CONSTRAINT TB_IF_GATE_DEF_PILOT_PK PRIMARY KEY (GATE_ID)
);

CREATE TABLE TB_IF_GATE_RESULT_PILOT (
    RESULT_ID        VARCHAR(40)   NOT NULL,
    GATE_ID          VARCHAR(20)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    RESULT_CD        VARCHAR(20)   NOT NULL,
    PASS_YN          CHAR(1)       NOT NULL,
    EVIDENCE         VARCHAR(1000),
    CHECKED_BY       VARCHAR(40),
    CHECKED_AT       VARCHAR(17),
    REMARK           VARCHAR(500),
    CONSTRAINT TB_IF_GATE_RESULT_PILOT_PK PRIMARY KEY (RESULT_ID)
);

-- INF-610 HA·DR 프로파일 파일럿
CREATE TABLE TB_IF_AVAIL_PROFILE_PILOT (
    PROFILE_ID       VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    OPS_HOURS_CD     VARCHAR(40),
    HA_YN            CHAR(1)       DEFAULT 'N',
    HA_MODE_CD       VARCHAR(40),
    CLUSTER_YN       CHAR(1)       DEFAULT 'N',
    DR_YN            CHAR(1)       DEFAULT 'N',
    DR_MODE_CD       VARCHAR(40),
    RTO_MINUTES      INT,
    RPO_MINUTES      INT,
    BACKUP_YN        CHAR(1)       DEFAULT 'N',
    MONITORING_YN    CHAR(1)       DEFAULT 'N',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_AVAIL_PROFILE_PILOT_PK PRIMARY KEY (PROFILE_ID)
);

-- INF-230 Application 배치/DB 연결 파일럿
CREATE TABLE TB_IF_APP_MAP_PILOT (
    MAP_ID           VARCHAR(40)   NOT NULL,
    APP_ID           VARCHAR(40)   NOT NULL,
    MAP_TYPE_CD      VARCHAR(20)   NOT NULL,
    REF_ID           VARCHAR(40)   NOT NULL,
    ROLE_CD          VARCHAR(40),
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_APP_MAP_PILOT_PK PRIMARY KEY (MAP_ID)
);

-- INF-620 용량 Snapshot 파일럿
CREATE TABLE TB_IF_CAPACITY_PILOT (
    SNAPSHOT_ID      VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    METRIC_SCOPE_CD  VARCHAR(20)   NOT NULL,
    CAPTURED_AT      VARCHAR(17)   NOT NULL,
    CPU_PCT          DECIMAL(6,2),
    MEM_PCT          DECIMAL(6,2),
    TPS              DECIMAL(14,2),
    RESP_P95_MS      DECIMAL(12,2),
    DB_CONN_PEAK     INT,
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_CAPACITY_PILOT_PK PRIMARY KEY (SNAPSHOT_ID)
);

-- INF-630 보안 프로파일 파일럿
CREATE TABLE TB_IF_SECURITY_PROFILE_PILOT (
    PROFILE_ID         VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD     VARCHAR(20)   NOT NULL,
    TARGET_ID          VARCHAR(40)   NOT NULL,
    SECURITY_GRADE_CD  VARCHAR(40),
    PERSONAL_INFO_YN   CHAR(1)       DEFAULT 'N',
    CREDIT_INFO_YN     CHAR(1)       DEFAULT 'N',
    FINANCIAL_TXN_YN   CHAR(1)       DEFAULT 'N',
    ADMIN_INFO_YN      CHAR(1)       DEFAULT 'N',
    EXTERNAL_CONN_YN   CHAR(1)       DEFAULT 'N',
    INTERNET_CONN_YN   CHAR(1)       DEFAULT 'N',
    ENCRYPTION_YN      CHAR(1)       DEFAULT 'N',
    KMS_HSM_YN         CHAR(1)       DEFAULT 'N',
    PAM_YN             CHAR(1)       DEFAULT 'N',
    EDR_YN             CHAR(1)       DEFAULT 'N',
    AUDIT_LOG_YN       CHAR(1)       DEFAULT 'N',
    AUTH_METHOD_CD     VARCHAR(40),
    NETWORK_ZONE_CD    VARCHAR(40),
    REMARK             VARCHAR(500),
    REG_USER_ID        VARCHAR(50),
    REG_DTM            VARCHAR(17),
    CHG_USER_ID        VARCHAR(50),
    CHG_DTM            VARCHAR(17),
    CONSTRAINT TB_IF_SECURITY_PROFILE_PILOT_PK PRIMARY KEY (PROFILE_ID)
);

-- INF-820 Migration Wave 파일럿
CREATE TABLE TB_IF_MIGRATION_WAVE_PILOT (
    WAVE_ID          VARCHAR(40)   NOT NULL,
    WAVE_NAME        VARCHAR(120)  NOT NULL,
    SEQUENCE_NO      INT           NOT NULL,
    PLANNED_START    VARCHAR(8),
    PLANNED_END      VARCHAR(8),
    STATUS_CD        VARCHAR(40)   DEFAULT 'PLANNED',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_MIGRATION_WAVE_PILOT_PK PRIMARY KEY (WAVE_ID)
);

-- INF-810 7R 전환계획 파일럿
CREATE TABLE TB_IF_MIGRATION_PLAN_PILOT (
    PLAN_ID              VARCHAR(40)   NOT NULL,
    WAVE_ID              VARCHAR(40),
    TARGET_TYPE_CD       VARCHAR(20)   NOT NULL,
    TARGET_ID            VARCHAR(40)   NOT NULL,
    STRATEGY_7R_CD       VARCHAR(40)   NOT NULL,
    CURRENT_PLATFORM_CD  VARCHAR(40),
    TARGET_PLATFORM_CD   VARCHAR(40),
    DIFFICULTY_CD        VARCHAR(20),
    STATUS_CD            VARCHAR(40)   DEFAULT 'TARGET_DEFINED',
    REMARK               VARCHAR(1000),
    REG_USER_ID          VARCHAR(50),
    REG_DTM              VARCHAR(17),
    CHG_USER_ID          VARCHAR(50),
    CHG_DTM              VARCHAR(17),
    CONSTRAINT TB_IF_MIGRATION_PLAN_PILOT_PK PRIMARY KEY (PLAN_ID)
);

-- INF-710 라이선스 계약 파일럿
CREATE TABLE TB_IF_LICENSE_PILOT (
    LICENSE_ID         VARCHAR(40)   NOT NULL,
    PRODUCT_NAME       VARCHAR(120)  NOT NULL,
    VENDOR_NAME        VARCHAR(120),
    LICENSE_MODEL_CD   VARCHAR(40),
    QTY                DECIMAL(12,2),
    ANNUAL_MAINT_AMT   DECIMAL(18,2),
    CURRENCY_CD        VARCHAR(10)   DEFAULT 'KRW',
    CONTRACT_END_DT    VARCHAR(10),
    MOBILITY_YN        CHAR(1)       DEFAULT 'N',
    REMARK             VARCHAR(500),
    REG_USER_ID        VARCHAR(50),
    REG_DTM            VARCHAR(17),
    CHG_USER_ID        VARCHAR(50),
    CHG_DTM            VARCHAR(17),
    CONSTRAINT TB_IF_LICENSE_PILOT_PK PRIMARY KEY (LICENSE_ID)
);

CREATE TABLE TB_IF_ASSET_LICENSE_PILOT (
    ASSET_ID           VARCHAR(40)   NOT NULL,
    LICENSE_ID         VARCHAR(40)   NOT NULL,
    ALLOCATED_QTY      DECIMAL(12,2),
    CONSTRAINT TB_IF_ASSET_LICENSE_PILOT_PK PRIMARY KEY (ASSET_ID, LICENSE_ID)
);

-- INF-730 비용 Snapshot 파일럿
CREATE TABLE TB_IF_COST_PILOT (
    COST_ID          VARCHAR(40)   NOT NULL,
    TARGET_TYPE_CD   VARCHAR(20)   NOT NULL,
    TARGET_ID        VARCHAR(40)   NOT NULL,
    PERIOD_YM        VARCHAR(6)    NOT NULL,
    SCENARIO_CD      VARCHAR(20)   NOT NULL,
    COST_TYPE_CD     VARCHAR(40)   NOT NULL,
    AMOUNT           DECIMAL(18,2) NOT NULL,
    CURRENCY_CD      VARCHAR(10)   DEFAULT 'KRW',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CONSTRAINT TB_IF_COST_PILOT_PK PRIMARY KEY (COST_ID)
);

-- INF-430 EOL/EOS 통합 뷰 (잔여일은 서비스에서 계산) — OS/MW/DB
CREATE VIEW V_IF_EOL_RISK AS
SELECT 'OS' AS SOURCE_CD,
       ASSET_ID AS OBJECT_ID,
       TRIM(COALESCE(OS_NAME, '') || CASE WHEN OS_VERSION IS NULL OR OS_VERSION = '' THEN '' ELSE ' ' || OS_VERSION END) AS OBJECT_NAME,
       ASSET_ID AS ASSET_ID,
       OS_EOL_DATE AS EOL_DATE
  FROM TB_IF_SERVER_ASSET_PILOT
 WHERE OS_EOL_DATE IS NOT NULL
UNION ALL
SELECT 'MW' AS SOURCE_CD,
       MW_ID AS OBJECT_ID,
       PRODUCT_NAME AS OBJECT_NAME,
       ASSET_ID AS ASSET_ID,
       EOL_DATE AS EOL_DATE
  FROM TB_IF_MW_INSTALL_PILOT
 WHERE EOL_DATE IS NOT NULL
UNION ALL
SELECT 'DB' AS SOURCE_CD,
       DB_ID AS OBJECT_ID,
       DB_NAME AS OBJECT_NAME,
       ASSET_ID AS ASSET_ID,
       EOL_DATE AS EOL_DATE
  FROM TB_IF_DB_INSTANCE_PILOT
 WHERE EOL_DATE IS NOT NULL;

-- INF-830/940 전환 매핑
CREATE VIEW V_IF_MIGRATION_MAPPING AS
SELECT P.PLAN_ID AS PLAN_ID,
       P.WAVE_ID AS WAVE_ID,
       W.WAVE_NAME AS WAVE_NAME,
       P.TARGET_TYPE_CD AS TARGET_TYPE_CD,
       P.TARGET_ID AS TARGET_ID,
       P.STRATEGY_7R_CD AS STRATEGY_7R_CD,
       P.CURRENT_PLATFORM_CD AS CURRENT_PLATFORM_CD,
       P.TARGET_PLATFORM_CD AS TARGET_PLATFORM_CD,
       P.DIFFICULTY_CD AS DIFFICULTY_CD,
       P.STATUS_CD AS STATUS_CD,
       P.REMARK AS GAP_REMARK
  FROM TB_IF_MIGRATION_PLAN_PILOT P
  LEFT JOIN TB_IF_MIGRATION_WAVE_PILOT W ON W.WAVE_ID = P.WAVE_ID;

-- INF-940 표10 TCO 비교 (cost_snapshot 집계, 기본 5Y)
CREATE VIEW V_IF_PROPOSAL_TCO AS
SELECT C.TARGET_TYPE_CD AS TARGET_TYPE_CD,
       C.TARGET_ID AS TARGET_ID,
       C.PERIOD_YM AS PERIOD_YM,
       MAX(C.CURRENCY_CD) AS CURRENCY_CD,
       5 AS YEARS,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' THEN C.AMOUNT ELSE 0 END) AS ASIS_ANNUAL,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' THEN C.AMOUNT ELSE 0 END) AS TOBE_ANNUAL,
       SUM(CASE WHEN C.SCENARIO_CD = 'MIG' THEN C.AMOUNT ELSE 0 END) AS MIGRATION_ONCE,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' THEN C.AMOUNT ELSE 0 END) * 5 AS ASIS_TCO,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' THEN C.AMOUNT ELSE 0 END) * 5
         + SUM(CASE WHEN C.SCENARIO_CD = 'MIG' THEN C.AMOUNT ELSE 0 END) AS TOBE_TCO,
       (SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' THEN C.AMOUNT ELSE 0 END) * 5)
         - (SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' THEN C.AMOUNT ELSE 0 END) * 5
            + SUM(CASE WHEN C.SCENARIO_CD = 'MIG' THEN C.AMOUNT ELSE 0 END)) AS DELTA_TCO,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' AND C.COST_TYPE_CD = 'HW' THEN C.AMOUNT ELSE 0 END) AS ASIS_HW,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' AND C.COST_TYPE_CD = 'CLOUD' THEN C.AMOUNT ELSE 0 END) AS ASIS_CLOUD,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' AND C.COST_TYPE_CD = 'MW' THEN C.AMOUNT ELSE 0 END) AS ASIS_MW,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' AND C.COST_TYPE_CD = 'DB' THEN C.AMOUNT ELSE 0 END) AS ASIS_DB,
       SUM(CASE WHEN C.SCENARIO_CD = 'ASIS' AND C.COST_TYPE_CD = 'OPS' THEN C.AMOUNT ELSE 0 END) AS ASIS_OPS,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' AND C.COST_TYPE_CD = 'HW' THEN C.AMOUNT ELSE 0 END) AS TOBE_HW,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' AND C.COST_TYPE_CD = 'CLOUD' THEN C.AMOUNT ELSE 0 END) AS TOBE_CLOUD,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' AND C.COST_TYPE_CD = 'MW' THEN C.AMOUNT ELSE 0 END) AS TOBE_MW,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' AND C.COST_TYPE_CD = 'DB' THEN C.AMOUNT ELSE 0 END) AS TOBE_DB,
       SUM(CASE WHEN C.SCENARIO_CD = 'TOBE' AND C.COST_TYPE_CD = 'OPS' THEN C.AMOUNT ELSE 0 END) AS TOBE_OPS
  FROM TB_IF_COST_PILOT C
 GROUP BY C.TARGET_TYPE_CD, C.TARGET_ID, C.PERIOD_YM;

-- INF-940 서버 인벤토리 (파일럿 서버 + Primary IP)
CREATE VIEW V_IF_SERVER_INVENTORY AS
SELECT S.SERVER_ID AS ASSET_ID,
       S.SERVER_NAME AS ASSET_NAME,
       S.TECH_ROLE AS TECH_ROLE_CD,
       S.ENV_CD AS ENV_CD,
       S.TIER_CD AS TIER_CD,
       S.STATUS_CD AS STATUS_CD,
       S.REMARK AS REMARK,
       EP.ADDRESS AS PRIMARY_IP
  FROM TB_IF_SERVER_PILOT S
  LEFT JOIN TB_IF_NETWORK_EP_PILOT EP
    ON EP.ASSET_ID = S.SERVER_ID AND EP.PRIMARY_YN = 'Y';

-- INF-940 서버군 용량 (Peak Snapshot 조인)
CREATE VIEW V_IF_SERVER_GROUP_CAPACITY AS
SELECT G.GROUP_ID AS GROUP_ID,
       G.GROUP_NAME AS GROUP_NAME,
       G.SYSTEM_ID AS SYSTEM_ID,
       G.TECH_ROLE_CD AS TECH_ROLE_CD,
       G.ENV_CD AS ENV_CD,
       G.TIER_CD AS TIER_CD,
       G.STATUS_CD AS STATUS_CD,
       G.ACTIVE_NODES AS ACTIVE_NODES,
       G.STANDBY_NODES AS STANDBY_NODES,
       G.DR_NODES AS DR_NODES,
       C.TPS AS PEAK_TPS,
       C.CPU_PCT AS PEAK_CPU_PCT,
       C.MEM_PCT AS PEAK_MEM_PCT,
       C.RESP_P95_MS AS PEAK_RESP_P95_MS
  FROM TB_IF_SERVER_GROUP_PILOT G
  LEFT JOIN TB_IF_CAPACITY_PILOT C
    ON C.TARGET_TYPE_CD = 'GROUP'
   AND C.TARGET_ID = G.GROUP_ID
   AND C.METRIC_SCOPE_CD = 'PEAK';
