-- 자동생성 DDL 초안
-- 실제 스키마·테이블스페이스·파티션·인덱스 기준은 DA/DBA 검토 후 확정한다.
CREATE TABLE SV_CUSTOMER (
    CUSTOMER_NO VARCHAR2(20) NOT NULL /* 고객번호 */,
    BASE_DATE CHAR(8) /* 기준일자 */,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL /* 고객명 */,
    CUSTOMER_GRADE VARCHAR2(10) /* 고객등급 */,
    BRANCH_CODE VARCHAR2(10) /* 영업점코드 */,
    TOTAL_BALANCE NUMBER(18,2) /* 총잔액 */,
    CONSTRAINT PK_SV_CUSTOMER PRIMARY KEY (CUSTOMER_NO)
);

COMMENT ON TABLE SV_CUSTOMER IS '고객 종합정보';
COMMENT ON COLUMN SV_CUSTOMER.CUSTOMER_NO IS '고객번호';
COMMENT ON COLUMN SV_CUSTOMER.BASE_DATE IS '기준일자';
COMMENT ON COLUMN SV_CUSTOMER.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN SV_CUSTOMER.CUSTOMER_GRADE IS '고객등급';
COMMENT ON COLUMN SV_CUSTOMER.BRANCH_CODE IS '영업점코드';
COMMENT ON COLUMN SV_CUSTOMER.TOTAL_BALANCE IS '총잔액';
