-- CRUD Meoy 단계별 세션 테이블 (JPA ddl-auto=update 로 생성)
-- 참고용 DDL

CREATE TABLE IF NOT EXISTS crud_step_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(64) NOT NULL,
  session_name VARCHAR(200),
  step_id VARCHAR(32) NOT NULL,
  step_title VARCHAR(120),
  step_order INT,
  status VARCHAR(32) NOT NULL,
  business_code VARCHAR(8),
  domain_code VARCHAR(64),
  answers_json CLOB,
  summary_md CLOB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  confirmed_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_step_session UNIQUE (session_id, step_id)
);
