-- 기존 H2 DB에 로그인 기능 반영 (tcf-om/scripts)
-- 실행: h2 shell 또는 IDE에서 nsight_om DB에 적용

ALTER TABLE OM_USER ADD COLUMN IF NOT EXISTS PASSWORD_HASH VARCHAR(200);

UPDATE OM_USER SET PASSWORD_HASH = NULL WHERE PASSWORD_HASH IS NOT NULL AND TRIM(PASSWORD_HASH) = '';

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-027', 'OM', 'OM.Auth.login', 'OM-AUT-0002', 'EXECUTE',
    'OmAuthLoginHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', 'OM 로그인'
);

-- PASSWORD_HASH 가 NULL 인 사용자는 tcf-om 재기동 시 OmUserPasswordInitializer 가 nsight01! 해시를 설정합니다.

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-028', 'OM', 'OM.Auth.logout', 'OM-AUT-0003', 'EXECUTE',
    'OmAuthLogoutHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', 'OM 로그아웃'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-029', 'OM', 'OM.Auth.session', 'OM-AUT-0004', 'INQUIRY',
    'OmAuthSessionInquiryHandler', 'ROLE_OM_AUTH', 'N', 5, 'Y', 'OM 세션 조회'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-030', 'OM', 'OM.Session.inquiry', 'OM-SES-0001', 'INQUIRY',
    'OmSessionInquiryHandler', 'ROLE_OM_AUTH', 'Y', 10, 'Y', '세션 목록 조회'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-031', 'OM', 'OM.Session.delete', 'OM-SES-0002', 'DELETE',
    'OmSessionDeleteHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', '세션 강제 종료'
);

MERGE INTO OM_MENU (
    MENU_ID, MENU_NAME, MENU_URL, PARENT_MENU_ID, SORT_ORDER, USE_YN
) KEY (MENU_ID) VALUES (
    'OM_SES', '세션 관리', '/om/admin/session.html', NULL, 16, 'Y'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-032', 'OM', 'OM.User.detail', 'OM-USR-0002', 'INQUIRY',
    'OmUserDetailHandler', 'ROLE_OM_AUTH', 'N', 5, 'Y', '사용자 상세'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-033', 'OM', 'OM.User.save', 'OM-USR-0003', 'UPDATE',
    'OmUserSaveHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', '사용자 등록'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-034', 'OM', 'OM.User.update', 'OM-USR-0004', 'UPDATE',
    'OmUserUpdateHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', '사용자 수정'
);

MERGE INTO OM_SERVICE_CATALOG (
    CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE, PROCESSING_TYPE,
    HANDLER_CLASS, AUTH_CODE, AUDIT_YN, TIMEOUT_SEC, USE_YN, DESCRIPTION
) KEY (CATALOG_ID) VALUES (
    'CAT-035', 'OM', 'OM.User.delete', 'OM-USR-0005', 'DELETE',
    'OmUserDeleteHandler', 'ROLE_OM_AUTH', 'Y', 5, 'Y', '사용자 삭제'
);
