CREATE TABLE IF NOT EXISTS TCF_GATEWAY_ROUTE (
    ROUTE_ID             VARCHAR(60)  NOT NULL,
    ENV_CODE             VARCHAR(20)  NOT NULL,
    ROUTE_GROUP_CODE     VARCHAR(30)  NOT NULL,
    ROUTE_GROUP_NAME     VARCHAR(100) NOT NULL,
    BUSINESS_CODE        VARCHAR(10)  NOT NULL,
    BUSINESS_NAME        VARCHAR(100) NOT NULL,
    TARGET_BASE_URL      VARCHAR(300) NOT NULL,
    CONTEXT_PATH         VARCHAR(100) NOT NULL,
    ONLINE_PATH          VARCHAR(100) DEFAULT '/online' NOT NULL,
    HEALTH_CHECK_PATH    VARCHAR(200),
    CONNECT_TIMEOUT_MS   INT DEFAULT 3000 NOT NULL,
    READ_TIMEOUT_MS      INT DEFAULT 5000 NOT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y' NOT NULL,
    SORT_ORDER           INT,
    DESCRIPTION          VARCHAR(500),
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_TCF_GATEWAY_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT UK_TCF_GATEWAY_ROUTE_01 UNIQUE (ENV_CODE, BUSINESS_CODE)
);

CREATE INDEX IF NOT EXISTS IX_TCF_GATEWAY_ROUTE_01 ON TCF_GATEWAY_ROUTE (ENV_CODE, BUSINESS_CODE, USE_YN);
CREATE INDEX IF NOT EXISTS IX_TCF_GATEWAY_ROUTE_02 ON TCF_GATEWAY_ROUTE (ENV_CODE, ROUTE_GROUP_CODE, USE_YN);

CREATE TABLE IF NOT EXISTS TCF_USER_SESSION (
    SESSION_ID           VARCHAR(100) NOT NULL,
    USER_ID              VARCHAR(50)  NOT NULL,
    USER_NAME            VARCHAR(100),
    BRANCH_ID            VARCHAR(20),
    CHANNEL_ID           VARCHAR(20),
    AUTH_GROUP_ID        VARCHAR(50),
    SESSION_TYPE         VARCHAR(20)  DEFAULT 'BUSINESS' NOT NULL,
    LOGIN_TIME           TIMESTAMP    NOT NULL,
    LAST_ACCESS_TIME     TIMESTAMP    NOT NULL,
    ABSOLUTE_EXPIRE_TIME TIMESTAMP    NOT NULL,
    CLIENT_IP            VARCHAR(50),
    USER_AGENT           VARCHAR(500),
    CENTER_ID            VARCHAR(20),
    WAS_ID               VARCHAR(50),
    STATUS               VARCHAR(20)  DEFAULT 'ACTIVE' NOT NULL,
    LOGOUT_TIME          TIMESTAMP,
    LOGOUT_REASON        VARCHAR(200),
    CREATED_AT           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_TCF_USER_SESSION PRIMARY KEY (SESSION_ID)
);

CREATE INDEX IF NOT EXISTS IX_TCF_USER_SESSION_01 ON TCF_USER_SESSION (USER_ID, STATUS);
CREATE INDEX IF NOT EXISTS IX_TCF_USER_SESSION_02 ON TCF_USER_SESSION (STATUS, ABSOLUTE_EXPIRE_TIME);

CREATE TABLE IF NOT EXISTS TCF_GATEWAY_TX_LOG (
    LOG_ID               VARCHAR(64)  NOT NULL,
    TX_TIME              VARCHAR(40)  NOT NULL,
    ENV_CODE             VARCHAR(20),
    BUSINESS_CODE        VARCHAR(10),
    SERVICE_ID           VARCHAR(100),
    TRANSACTION_CODE     VARCHAR(50),
    GUID                 VARCHAR(64),
    TRACE_ID             VARCHAR(64),
    USER_ID              VARCHAR(50),
    BRANCH_ID            VARCHAR(20),
    SESSION_ID           VARCHAR(100),
    TARGET_URL           VARCHAR(500),
    HTTP_STATUS          INT,
    RESULT_STATUS        VARCHAR(20),
    RESULT_CODE          VARCHAR(20),
    ERROR_CODE           VARCHAR(50),
    ELAPSED_TIME_MS      BIGINT,
    PHASE                VARCHAR(50),
    CONSTRAINT PK_TCF_GATEWAY_TX_LOG PRIMARY KEY (LOG_ID)
);

CREATE INDEX IF NOT EXISTS IX_TCF_GW_TX_01 ON TCF_GATEWAY_TX_LOG (GUID, TX_TIME DESC);
CREATE INDEX IF NOT EXISTS IX_TCF_GW_TX_02 ON TCF_GATEWAY_TX_LOG (SERVICE_ID, TX_TIME DESC);
CREATE INDEX IF NOT EXISTS IX_TCF_GW_TX_03 ON TCF_GATEWAY_TX_LOG (USER_ID, TX_TIME DESC);
CREATE INDEX IF NOT EXISTS IX_TCF_GW_TX_04 ON TCF_GATEWAY_TX_LOG (BUSINESS_CODE, TX_TIME DESC);
