package com.nh.nsight.marketing.om.support;

import org.springframework.jdbc.core.JdbcTemplate;

final class ServiceCatalogSeedData {
    private ServiceCatalogSeedData() {}

    private record Entry(
            String catalogId,
            String businessCode,
            String serviceId,
            String transactionCode,
            String processingType,
            String handlerClass,
            String authCode,
            String auditYn,
            int timeoutSec,
            String useYn,
            String description) {}

    private static final Entry[] ALL = {
            entry("CAT-001", "SV", "SV.Sample.inquiry", "SV-INQ-0001", "INQUIRY",
                    "SvSampleHandler", "ROLE_SV_INQ", "N", 5, "Y", "SV 샘플 조회"),
            entry("CAT-002", "SV", "SV.Customer.selectSummary", "SV-INQ-0002", "INQUIRY",
                    "SvCustomerHandler", "ROLE_SV_INQ", "Y", 3, "Y", "고객요약 조회"),
            entry("CAT-003", "OM", "OM.Dashboard.inquiry", "OM-DSH-0001", "INQUIRY",
                    "OmDashboardHandler", "ROLE_OM_DSH", "N", 5, "Y", "운영 대시보드"),
            entry("CAT-073", "OM", "OM.Dashboard.reset", "OM-DSH-0002", "EXECUTE",
                    "OmDashboardHandler", "ROLE_OM_DSH", "Y", 60, "Y", "대시보드 스냅샷 DB 초기화"),
            entry("CAT-004", "OM", "OM.TransactionLog.inquiry", "OM-TXL-0001", "INQUIRY",
                    "OmTransactionLogHandler", "ROLE_OM_TXL", "N", 10, "Y", "거래로그 조회"),
            entry("CAT-005", "OM", "OM.ServiceCatalog.inquiry", "OM-SVC-0001", "INQUIRY",
                    "OmServiceCatalogHandler", "ROLE_OM_SVC", "N", 5, "Y", "ServiceId 카탈로그"),
            entry("CAT-006", "OM", "OM.User.inquiry", "OM-USR-0001", "INQUIRY",
                    "OmUserHandler", "ROLE_OM_AUTH", "N", 5, "Y", "사용자 조회"),
            entry("CAT-007", "OM", "OM.Menu.inquiry", "OM-MNU-0001", "INQUIRY",
                    "OmMenuHandler", "ROLE_OM_AUTH", "N", 5, "Y", "메뉴 조회"),
            entry("CAT-079", "OM", "OM.Menu.save", "OM-MNU-0002", "UPDATE",
                    "OmMenuHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "메뉴 등록"),
            entry("CAT-080", "OM", "OM.Menu.detail", "OM-MNU-0003", "INQUIRY",
                    "OmMenuHandler", "ROLE_OM_AUTH", "N", 5, "Y", "메뉴 상세"),
            entry("CAT-081", "OM", "OM.Menu.update", "OM-MNU-0004", "UPDATE",
                    "OmMenuHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "메뉴 수정"),
            entry("CAT-082", "OM", "OM.Menu.delete", "OM-MNU-0005", "DELETE",
                    "OmMenuHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "메뉴 삭제"),
            entry("CAT-008", "OM", "OM.AuthGroup.inquiry", "OM-AUT-0001", "INQUIRY",
                    "OmAuthGroupHandler", "ROLE_OM_AUTH", "N", 5, "Y", "권한그룹 조회"),
            entry("CAT-075", "OM", "OM.AuthGroup.save", "OM-AGP-0001", "UPDATE",
                    "OmAuthGroupHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "권한그룹 등록"),
            entry("CAT-076", "OM", "OM.AuthGroup.detail", "OM-AGP-0002", "INQUIRY",
                    "OmAuthGroupHandler", "ROLE_OM_AUTH", "N", 5, "Y", "권한그룹 상세"),
            entry("CAT-077", "OM", "OM.AuthGroup.update", "OM-AGP-0003", "UPDATE",
                    "OmAuthGroupHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "권한그룹 수정"),
            entry("CAT-078", "OM", "OM.AuthGroup.delete", "OM-AGP-0004", "DELETE",
                    "OmAuthGroupHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "권한그룹 삭제"),
            entry("CAT-009", "OM", "OM.AuditLog.inquiry", "OM-AUD-0001", "INQUIRY",
                    "OmAuditLogHandler", "ROLE_OM_AUD", "Y", 10, "Y", "감사로그 조회"),
            entry("CAT-074", "OM", "OM.AuditLog.deleteAll", "OM-AUD-0002", "DELETE",
                    "OmAuditLogHandler", "ROLE_OM_AUD", "Y", 30, "Y", "감사로그 전체 삭제"),
            entry("CAT-010", "OM", "OM.ErrorCode.inquiry", "OM-ERR-0001", "INQUIRY",
                    "OmErrorCodeHandler", "ROLE_OM_ERR", "N", 5, "Y", "오류코드 조회"),
            entry("CAT-011", "OM", "OM.Batch.inquiry", "OM-BAT-0001", "INQUIRY",
                    "OmBatchHandler", "ROLE_OM_BAT", "N", 10, "Y", "배치/스케줄 조회"),
            entry("CAT-012", "OM", "OM.HealthCheck.inquiry", "OM-HLT-0001", "INQUIRY",
                    "OmHealthCheckHandler", "ROLE_OM_HLT", "N", 5, "Y", "Health Check 조회"),
            entry("CAT-111", "OM", "OM.Runtime.inquiry", "OM-RTM-0001", "INQUIRY",
                    "OmRuntimeHandler", "ROLE_OM_RTM", "N", 60, "Y", "런타임 진단"),
            entry("CAT-013", "OM", "OM.SystemConfig.inquiry", "OM-CFG-0001", "INQUIRY",
                    "OmSystemConfigHandler", "ROLE_OM_CFG", "N", 5, "Y", "환경설정 조회"),
            entry("CAT-014", "OM", "OM.FileDownload.inquiry", "OM-FIL-0001", "INQUIRY",
                    "OmFileDownloadHandler", "ROLE_OM_FIL", "Y", 10, "Y", "파일 다운로드 이력"),
            entry("CAT-015", "OM", "OM.CommonCode.inquiry", "OM-CDC-0001", "INQUIRY",
                    "OmCommonCodeHandler", "ROLE_OM_CDC", "N", 5, "Y", "공통코드 목록 조회"),
            entry("CAT-016", "OM", "OM.CommonCode.save", "OM-CDC-0002", "UPDATE",
                    "OmCommonCodeHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 등록"),
            entry("CAT-017", "OM", "OM.CommonCode.detail", "OM-CDC-0003", "INQUIRY",
                    "OmCommonCodeHandler", "ROLE_OM_CDC", "N", 5, "Y", "공통코드 단건 조회"),
            entry("CAT-018", "OM", "OM.CommonCode.update", "OM-CDC-0004", "UPDATE",
                    "OmCommonCodeHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 수정"),
            entry("CAT-019", "OM", "OM.CommonCode.delete", "OM-CDC-0005", "DELETE",
                    "OmCommonCodeHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 삭제"),
            entry("CAT-020", "OM", "OM.ErrorCode.save", "OM-ERR-0002", "UPDATE",
                    "OmErrorCodeHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 등록"),
            entry("CAT-021", "OM", "OM.Batch.execute", "OM-BAT-0002", "EXECUTE",
                    "OmBatchHandler", "ROLE_OM_BAT", "Y", 30, "Y", "배치 재실행"),
            entry("CAT-022", "OM", "OM.FunctionAuth.inquiry", "OM-FAU-0001", "INQUIRY",
                    "OmFunctionAuthHandler", "ROLE_OM_AUTH", "N", 5, "Y", "기능권한 조회"),
            entry("CAT-093", "OM", "OM.FunctionAuth.save", "OM-FAU-0002", "UPDATE",
                    "OmFunctionAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "기능권한 등록"),
            entry("CAT-094", "OM", "OM.FunctionAuth.detail", "OM-FAU-0003", "INQUIRY",
                    "OmFunctionAuthHandler", "ROLE_OM_AUTH", "N", 5, "Y", "기능권한 상세"),
            entry("CAT-095", "OM", "OM.FunctionAuth.update", "OM-FAU-0004", "UPDATE",
                    "OmFunctionAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "기능권한 수정"),
            entry("CAT-096", "OM", "OM.FunctionAuth.delete", "OM-FAU-0005", "DELETE",
                    "OmFunctionAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "기능권한 삭제"),
            entry("CAT-023", "OM", "OM.DataAuth.inquiry", "OM-DAU-0001", "INQUIRY",
                    "OmDataAuthHandler", "ROLE_OM_AUTH", "N", 5, "Y", "데이터권한 조회"),
            entry("CAT-024", "OM", "OM.AuthHistory.inquiry", "OM-AHT-0001", "INQUIRY",
                    "OmAuthHistoryHandler", "ROLE_OM_AUTH", "Y", 10, "Y", "권한이력 조회"),
            entry("CAT-112", "OM", "OM.AuthHistory.deleteAll", "OM-AHT-0002", "DELETE",
                    "OmAuthHistoryHandler", "ROLE_OM_AUTH", "Y", 30, "Y", "권한이력 전체 삭제"),
            entry("CAT-025", "OM", "OM.Cache.inquiry", "OM-CCH-0001", "INQUIRY",
                    "OmCacheHandler", "ROLE_OM_CACHE", "N", 5, "Y", "Cache 조회"),
            entry("CAT-026", "OM", "OM.Cache.delete", "OM-CCH-0002", "DELETE",
                    "OmCacheHandler", "ROLE_OM_CACHE", "Y", 10, "Y", "Cache 삭제"),
            entry("CAT-027", "OM", "OM.Auth.login", "OM-AUT-0002", "EXECUTE",
                    "OmAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "OM 로그인"),
            entry("CAT-028", "OM", "OM.Auth.logout", "OM-AUT-0003", "EXECUTE",
                    "OmAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "OM 로그아웃"),
            entry("CAT-029", "OM", "OM.Auth.session", "OM-AUT-0004", "INQUIRY",
                    "OmAuthHandler", "ROLE_OM_AUTH", "N", 5, "Y", "OM 세션 조회"),
            entry("CAT-106", "OM", "OM.Auth.ssoLogin", "OM-AUT-0005", "EXECUTE",
                    "OmAuthHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "OM SSO 로그인"),
            entry("CAT-030", "OM", "OM.Session.inquiry", "OM-SES-0001", "INQUIRY",
                    "OmSessionHandler", "ROLE_OM_AUTH", "Y", 10, "Y", "세션 목록 조회"),
            entry("CAT-031", "OM", "OM.Session.delete", "OM-SES-0002", "DELETE",
                    "OmSessionHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "세션 강제 종료"),
            entry("CAT-032", "OM", "OM.User.detail", "OM-USR-0002", "INQUIRY",
                    "OmUserHandler", "ROLE_OM_AUTH", "N", 5, "Y", "사용자 상세"),
            entry("CAT-033", "OM", "OM.User.save", "OM-USR-0003", "UPDATE",
                    "OmUserHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "사용자 등록"),
            entry("CAT-034", "OM", "OM.User.update", "OM-USR-0004", "UPDATE",
                    "OmUserHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "사용자 수정"),
            entry("CAT-035", "OM", "OM.User.delete", "OM-USR-0005", "DELETE",
                    "OmUserHandler", "ROLE_OM_AUTH", "Y", 5, "Y", "사용자 삭제"),
            entry("CAT-036", "OM", "OM.TransactionLog.deleteAll", "OM-TXL-0002", "DELETE",
                    "OmTransactionLogHandler", "ROLE_OM_TXL", "Y", 30, "Y", "거래로그 전체 삭제"),
            entry("CAT-037", "OM", "OM.ServiceCatalog.save", "OM-SVC-0002", "UPDATE",
                    "OmServiceCatalogHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 등록"),
            entry("CAT-038", "OM", "OM.ServiceCatalog.detail", "OM-SVC-0003", "INQUIRY",
                    "OmServiceCatalogHandler", "ROLE_OM_SVC", "N", 5, "Y", "ServiceId 상세"),
            entry("CAT-039", "OM", "OM.ServiceCatalog.update", "OM-SVC-0004", "UPDATE",
                    "OmServiceCatalogHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 수정"),
            entry("CAT-040", "OM", "OM.ServiceCatalog.delete", "OM-SVC-0005", "DELETE",
                    "OmServiceCatalogHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 삭제"),
            entry("CAT-041", "OM", "OM.ErrorCode.detail", "OM-ERR-0003", "INQUIRY",
                    "OmErrorCodeHandler", "ROLE_OM_ERR", "N", 5, "Y", "오류코드 상세"),
            entry("CAT-042", "OM", "OM.ErrorCode.update", "OM-ERR-0004", "UPDATE",
                    "OmErrorCodeHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 수정"),
            entry("CAT-043", "OM", "OM.ErrorCode.delete", "OM-ERR-0005", "DELETE",
                    "OmErrorCodeHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 삭제"),
            entry("CAT-044", "OM", "OM.Batch.deleteAll", "OM-BAT-0003", "DELETE",
                    "OmBatchHandler", "ROLE_OM_BAT", "Y", 30, "Y", "배치 실행이력 전체 삭제"),
            entry("CAT-045", "OM", "OM.Sample.inquiry", "OM-INQ-0001", "INQUIRY",
                    "OmSampleHandler", "ROLE_OM_AUTH", "N", 5, "Y", "OM 샘플 조회"),
            entry("CAT-046", "CC", "CC.Sample.inquiry", "CC-INQ-0001", "INQUIRY",
                    "CcSampleInquiryHandler", "ROLE_CC_INQ", "N", 5, "Y", "CC 샘플 조회"),
            entry("CAT-047", "IC", "IC.Sample.inquiry", "IC-INQ-0001", "INQUIRY",
                    "IcSampleHandler", "ROLE_IC_INQ", "N", 5, "Y", "IC 샘플 조회"),
            entry("CAT-074", "IC", "IC.Customer.inquiry", "IC-INQ-0002", "INQUIRY",
                    "IcCustomerHandler", "ROLE_IC_INQ", "Y", 5, "Y", "IC 고객상세 조회(SV 연동)"),
            entry("CAT-075", "SV", "SV.Integration.icSample", "SV-INT-0001", "INQUIRY",
                    "SvIntegrationHandler", "ROLE_SV_INQ", "N", 5, "Y", "SV→IC 연동 샘플 조회"),
            entry("CAT-048", "PC", "PC.Sample.inquiry", "PC-INQ-0001", "INQUIRY",
                    "PcSampleHandler", "ROLE_PC_INQ", "N", 5, "Y", "PC 샘플 조회"),
            entry("CAT-049", "BC", "BC.Sample.inquiry", "BC-INQ-0001", "INQUIRY",
                    "BcSampleInquiryHandler", "ROLE_BC_INQ", "N", 5, "Y", "BC 샘플 조회"),
            entry("CAT-050", "MS", "MS.Sample.inquiry", "MS-INQ-0001", "INQUIRY",
                    "MsSampleHandler", "ROLE_MS_INQ", "N", 5, "Y", "MS 샘플 조회"),
            entry("CAT-051", "PD", "PD.Sample.inquiry", "PD-INQ-0001", "INQUIRY",
                    "PdSampleHandler", "ROLE_PD_INQ", "N", 5, "Y", "PD 샘플 조회"),
            entry("CAT-052", "CM", "CM.Sample.inquiry", "CM-INQ-0001", "INQUIRY",
                    "CmSampleInquiryHandler", "ROLE_CM_INQ", "N", 5, "Y", "CM 샘플 조회"),
            entry("CAT-053", "EB", "EB.Sample.inquiry", "EB-INQ-0001", "INQUIRY",
                    "EbSampleHandler", "ROLE_EB_INQ", "N", 5, "Y", "EB 샘플 조회"),
            entry("CAT-113", "EB", "EB.SystemTx.inquiry", "EB-STX-0001", "INQUIRY",
                    "EbSystemTxHandler", "ROLE_EB_INQ", "N", 5, "Y", "EB 시스템 거래 현황(19410)"),
            entry("CAT-054", "EP", "EP.Sample.inquiry", "EP-INQ-0001", "INQUIRY",
                    "EpSampleHandler", "ROLE_EP_INQ", "N", 5, "Y", "EP 샘플 조회"),
            entry("CAT-055", "BP", "BP.Sample.inquiry", "BP-INQ-0001", "INQUIRY",
                    "BpSampleInquiryHandler", "ROLE_BP_INQ", "N", 5, "Y", "BP 샘플 조회"),
            entry("CAT-056", "BD", "BD.Sample.inquiry", "BD-INQ-0001", "INQUIRY",
                    "BdSampleInquiryHandler", "ROLE_BD_INQ", "N", 5, "Y", "BD 샘플 조회"),
            entry("CAT-057", "SS", "SS.Sample.inquiry", "SS-INQ-0001", "INQUIRY",
                    "SsSampleHandler", "ROLE_SS_INQ", "N", 5, "Y", "SS 샘플 조회"),
            entry("CAT-058", "CS", "CS.Sample.inquiry", "CS-INQ-0001", "INQUIRY",
                    "CsSampleInquiryHandler", "ROLE_CS_INQ", "N", 5, "Y", "CS 샘플 조회"),
            entry("CAT-059", "CT", "CT.Sample.inquiry", "CT-INQ-0001", "INQUIRY",
                    "CtSampleInquiryHandler", "ROLE_CT_INQ", "N", 5, "Y", "CT 샘플 조회"),
            entry("CAT-060", "MG", "MG.Sample.inquiry", "MG-INQ-0001", "INQUIRY",
                    "MgSampleHandler", "ROLE_MG_INQ", "N", 5, "Y", "MG 샘플 조회"),
            entry("CAT-061", "SV", "SV.Customer.detail", "SV-INQ-0003", "INQUIRY",
                    "SvCustomerDetailHandler", "ROLE_SV_INQ", "Y", 5, "Y", "고객 상세 조회"),
            entry("CAT-062", "SV", "SV.Customer.register", "SV-REG-0001", "CREATE",
                    "SvCustomerRegisterHandler", "ROLE_SV_INQ", "Y", 5, "Y", "고객 등록"),
            entry("CAT-063", "CM", "CM.Campaign.list", "CM-INQ-0002", "INQUIRY",
                    "CmCampaignListHandler", "ROLE_CM_INQ", "N", 5, "Y", "캠페인 목록 조회"),
            entry("CAT-064", "MG", "MG.Message.send", "MG-EXE-0001", "EXECUTE",
                    "MgMessageSendHandler", "ROLE_MG_INQ", "Y", 10, "Y", "메시지 발송"),
            entry("CAT-065", "UD", "UD.File.list", "UD-LST-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "N", 10, "Y", "파일 목록 조회"),
            entry("CAT-066", "UD", "UD.File.upload", "UD-UPL-0001", "CREATE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 30, "Y", "파일 업로드"),
            entry("CAT-067", "UD", "UD.File.download", "UD-DWN-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 30, "Y", "파일 다운로드"),
            entry("CAT-068", "UD", "UD.File.detail", "UD-DTL-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "N", 5, "Y", "파일 상세 조회"),
            entry("CAT-069", "UD", "UD.File.update", "UD-UPD-0001", "UPDATE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 5, "Y", "파일 메타 수정"),
            entry("CAT-070", "UD", "UD.File.delete", "UD-DEL-0001", "DELETE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 5, "Y", "파일 삭제"),
            entry("CAT-071", "ET", "ET.TransactionIo.list", "ET-LST-0001", "INQUIRY",
                    "EtTransactionIoListHandler", "ROLE_ET_INQ", "N", 5, "N", "거래 I/O 목록 (레거시)"),
            entry("CAT-072", "ET", "ET.TransactionIo.detail", "ET-DTL-0001", "INQUIRY",
                    "EtTransactionIoDetailHandler", "ROLE_ET_INQ", "N", 5, "N", "거래 I/O 상세 (레거시)"),
            entry("CAT-083", "OM", "OM.Deploy.buildRequest", "OM-DPL-0001", "UPDATE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 10, "Y", "배포 Gradle 빌드 요청"),
            entry("CAT-084", "OM", "OM.Deploy.buildStatus", "OM-DPL-0002", "INQUIRY",
                    "OmDeployHandler", "ROLE_OM_DEP", "N", 5, "Y", "배포 빌드 상태 조회"),
            entry("CAT-085", "OM", "OM.Deploy.deployRequest", "OM-DPL-0003", "UPDATE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 10, "Y", "배포 요청 등록"),
            entry("CAT-086", "OM", "OM.Deploy.approve", "OM-DPL-0004", "UPDATE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 10, "Y", "배포 승인"),
            entry("CAT-087", "OM", "OM.Deploy.execute", "OM-DPL-0005", "EXECUTE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 300, "Y", "배포 실행"),
            entry("CAT-088", "OM", "OM.Deploy.history", "OM-DPL-0006", "INQUIRY",
                    "OmDeployHandler", "ROLE_OM_DEP", "N", 10, "Y", "배포 이력 조회"),
            entry("CAT-089", "OM", "OM.Deploy.logInquiry", "OM-DPL-0007", "INQUIRY",
                    "OmDeployHandler", "ROLE_OM_DEP", "N", 10, "Y", "배포 로그 조회"),
            entry("CAT-090", "OM", "OM.Deploy.rollbackRequest", "OM-DPL-0008", "UPDATE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 10, "Y", "배포 롤백 요청"),
            entry("CAT-091", "OM", "OM.Deploy.healthCheck", "OM-DPL-0009", "INQUIRY",
                    "OmDeployHandler", "ROLE_OM_DEP", "N", 10, "Y", "배포 Health Check"),
            entry("CAT-092", "OM", "OM.Deploy.deleteAll", "OM-DPL-0010", "DELETE",
                    "OmDeployHandler", "ROLE_OM_DEP", "Y", 30, "Y", "배포 요청·이력 초기화"),
            entry("CAT-097", "OM", "OM.TransactionControl.inquiry", "OM-TXC-0001", "INQUIRY",
                    "OmTransactionControlHandler", "ROLE_OM_TXC", "N", 10, "Y", "거래통제 조회"),
            entry("CAT-098", "OM", "OM.TransactionControl.save", "OM-TXC-0002", "UPDATE",
                    "OmTransactionControlHandler", "ROLE_OM_TXC", "Y", 5, "Y", "거래통제 등록"),
            entry("CAT-099", "OM", "OM.TransactionControl.delete", "OM-TXC-0003", "DELETE",
                    "OmTransactionControlHandler", "ROLE_OM_TXC", "Y", 5, "Y", "거래통제 삭제"),
            entry("CAT-100", "OM", "OM.TransactionControl.update", "OM-TXC-0004", "UPDATE",
                    "OmTransactionControlHandler", "ROLE_OM_TXC", "Y", 5, "Y", "거래통제 수정"),
            entry("CAT-101", "OM", "OM.TimeoutPolicy.inquiry", "OM-TMO-0001", "INQUIRY",
                    "OmTimeoutPolicyHandler", "ROLE_OM_TMO", "N", 10, "Y", "Timeout 정책 조회"),
            entry("CAT-102", "OM", "OM.TimeoutPolicy.save", "OM-TMO-0002", "UPDATE",
                    "OmTimeoutPolicyHandler", "ROLE_OM_TMO", "Y", 5, "Y", "Timeout 정책 등록"),
            entry("CAT-103", "OM", "OM.TimeoutPolicy.update", "OM-TMO-0003", "UPDATE",
                    "OmTimeoutPolicyHandler", "ROLE_OM_TMO", "Y", 5, "Y", "Timeout 정책 수정"),
            entry("CAT-104", "OM", "OM.TimeoutPolicy.delete", "OM-TMO-0004", "DELETE",
                    "OmTimeoutPolicyHandler", "ROLE_OM_TMO", "Y", 5, "Y", "Timeout 정책 삭제"),
            entry("CAT-105", "OM", "OM.MessageStructure.inquiry", "OM-MSG-0001", "INQUIRY",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "N", 10, "Y", "전문구조 조회"),
            entry("CAT-106", "OM", "OM.MessageStructure.detail", "OM-MSG-0002", "INQUIRY",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "N", 5, "Y", "전문구조 상세"),
            entry("CAT-107", "OM", "OM.MessageStructure.frameworkInquiry", "OM-MSG-0003", "INQUIRY",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "N", 5, "Y", "TCF 표준 전문 템플릿"),
            entry("CAT-108", "OM", "OM.MessageStructure.save", "OM-MSG-0004", "UPDATE",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "Y", 5, "Y", "전문구조 등록"),
            entry("CAT-109", "OM", "OM.MessageStructure.update", "OM-MSG-0005", "UPDATE",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "Y", 5, "Y", "전문구조 수정"),
            entry("CAT-110", "OM", "OM.MessageStructure.delete", "OM-MSG-0006", "DELETE",
                    "OmMessageStructureHandler", "ROLE_OM_MSG", "Y", 5, "Y", "전문구조 삭제")
    };

    static void mergeAll(JdbcTemplate jdbcTemplate) {
        for (Entry seed : ALL) {
            jdbcTemplate.update("""
                    MERGE INTO OM_SERVICE_CATALOG (CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE,
                                                   PROCESSING_TYPE, HANDLER_CLASS, AUTH_CODE, AUDIT_YN,
                                                   TIMEOUT_SEC, USE_YN, DESCRIPTION)
                    KEY (CATALOG_ID)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    seed.catalogId(), seed.businessCode(), seed.serviceId(), seed.transactionCode(),
                    seed.processingType(), seed.handlerClass(), seed.authCode(), seed.auditYn(),
                    seed.timeoutSec(), seed.useYn(), seed.description());
        }
    }

    private static Entry entry(
            String catalogId,
            String businessCode,
            String serviceId,
            String transactionCode,
            String processingType,
            String handlerClass,
            String authCode,
            String auditYn,
            int timeoutSec,
            String useYn,
            String description) {
        return new Entry(catalogId, businessCode, serviceId, transactionCode, processingType,
                handlerClass, authCode, auditYn, timeoutSec, useYn, description);
    }
}
