param([string]$Root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path)
$ErrorActionPreference='Stop';$failures=[System.Collections.Generic.List[string]]::new();try{$Root=(Resolve-Path $Root).Path}catch{Write-Error "Invalid root: $Root";exit 1}
$required=@('AGENTS.md','README.md','docs/quickstart.md','docs/migration-from-claude.md','agents/analyst.md','agents/builder.md','agents/qa.md','skills/harness/SKILL.md','skills/harness/orchestrator-sample/SKILL.md','skills/harness/references/agent-design-patterns.md','skills/harness/references/orchestrator-template.md','skills/harness/references/codex-tool-mapping.md','skills/harness/orchestrator-sample/scripts/run-simulation.ps1','skills/harness/orchestrator-sample/scripts/run-simulation.bat','skills/harness/orchestrator-sample/scripts/run-simulation.sh')
foreach($r in $required){if(-not(Test-Path (Join-Path $Root $r) -PathType Leaf)){$failures.Add("Missing file: $r")}}
foreach($role in @('analyst','builder','qa')){$p=Join-Path $Root "agents/$role.md";if(Test-Path $p){$n=([regex]::Matches((Get-Content -Raw -Encoding UTF8 $p),'(?m)^## [^#\r\n]+$')).Count;if($n-ne 6){$failures.Add("Role sections: $role ($n/6)")}}}
foreach($r in @('skills/harness/SKILL.md','skills/harness/orchestrator-sample/SKILL.md')){$p=Join-Path $Root $r;if(Test-Path $p){$c=Get-Content -Raw -Encoding UTF8 $p;if($c-notmatch'(?s)^---\s*\r?\n.*?name:\s*[^\r\n]+.*?description:\s*[^\r\n]+.*?\r?\n---'){$failures.Add("Invalid skill frontmatter: $r")}}}
$scan=Get-ChildItem $Root -Recurse -File|Where-Object{$_.Extension-in@('.md','.ps1','.bat','.sh')-and$_.FullName-notlike'*docs\migration-from-claude.md'-and$_.FullName-notlike'*tests\*'-and$_.FullName-notlike'*scripts\verify-codex-harness.*'}
$forbidden='(?i)(\.claude[\\/]|(?<![-\w])CLAUDE\.md|\.claude-plugin|Claude CLI|Anthropic API)'
foreach($f in $scan){if(Select-String -LiteralPath $f.FullName -Pattern $forbidden -Encoding UTF8){$failures.Add("Forbidden runtime reference: "+$f.FullName.Substring($Root.Length+1))}}
foreach($file in Get-ChildItem $Root -Recurse -Filter '*.md' -File){$c=Get-Content -Raw -Encoding UTF8 $file.FullName;foreach($m in [regex]::Matches($c,'\[[^\]]+\]\((?!https?://|#)([^)]+)\)')){$target=($m.Groups[1].Value-split'#')[0];if($target){$resolved=Join-Path $file.DirectoryName ([uri]::UnescapeDataString($target));if(-not(Test-Path $resolved)){$failures.Add("Broken link: "+$file.FullName.Substring($Root.Length+1)+" -> $target")}}}}
if(Test-Path (Join-Path $Root '.github/scripts/check_claude_plugin.sh')){$failures.Add('Legacy plugin check still exists')}
if($failures.Count){$failures|ForEach-Object{Write-Error $_ -ErrorAction Continue};exit 1};Write-Host 'Codex harness verification passed.';exit 0
