CREATE TABLE IF NOT EXISTS SV_SAMPLE (
    SAMPLE_KEY   VARCHAR(30) PRIMARY KEY,
    SAMPLE_NAME  VARCHAR(100) NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SV.Customer.selectSummary 로컬(H2) 테이블.
-- 운영은 RDW_CUSTOMER 등 다중 테이블 JOIN으로 동일 컬럼을 구성.
CREATE TABLE IF NOT EXISTS SV_CUSTOMER (
    CUSTOMER_NO           VARCHAR(20) PRIMARY KEY,
    CUSTOMER_NAME         VARCHAR(50) NOT NULL,
    CUSTOMER_GRADE        VARCHAR(10),
    BRANCH_CODE           VARCHAR(10),
    BRANCH_NAME           VARCHAR(50),
    TOTAL_BALANCE         BIGINT DEFAULT 0,
    LOAN_BALANCE          BIGINT DEFAULT 0,
    PRODUCT_COUNT         INT DEFAULT 0,
    LAST_TRANSACTION_DATE VARCHAR(8)
);
