/**
 * 챕터 번호 → znsight-capacity-word 원본 파일 매핑
 */
module.exports.CHAPTER_SOURCES = {
  1: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['1. 도입', '2. 공통'] }] },
  2: { files: [{ name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['1. 문서 목적', '2. Tomcat 적용'] }] },
  3: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['1. 도입', '3. 전체 산정'] }] },
  4: { files: [{ name: '환경셋팅_최종_docx.txt', slice: ['2. WebTopSuite', '4. Spring'] }] },
  5: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['2. 공통', '3. 전체'] }] },
  6: { files: [{ name: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt' }] },
  7: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['3. 전체 산정', '4. 1단계'] }] },
  8: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['4. 1단계', '6. 3단계'] }] },
  9: { files: [
    { name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['6. 3단계', '8. 5단계'] },
    { name: '720_TPS_기준_용량_보고서_docx.txt', slice: ['2.2', '2.4'] },
  ]},
  10: { files: [{ name: 'TPS와_TPMC의_관계_분석_및_실효_처리량_산정_가이드_docx.txt' }] },
  11: { files: [
    { name: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt' },
    { name: '720_TPS_기준_용량_보고서_docx.txt', slice: ['3', '4'] },
  ]},
  12: { files: [
    { name: 'NSIGHT_JVM_셋팅_가이드_docx.txt', slice: ['4. Heap', '7. Thread'] },
    { name: 'OS_메모리와_JVM_Heap_관계_docx.txt' },
  ]},
  13: { files: [
    { name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['8. 5단계', '10. 7단계'] },
    { name: 'NSIGHT_L4_설정_가이드_docx.txt', slice: ['3. 트래픽', '4. L4 핵심'] },
  ]},
  14: { files: [{ name: '환경셋팅_최종_docx.txt', slice: ['10. 최종 환경설정 요약표', null] }] },
  15: { files: [{ name: '환경셋팅_최종_docx.txt', slice: ['1. 공통 기준', '2. WebTopSuite'] }] },
  16: { files: [{ name: 'NSIGHT_Timeout_Setting_Guide_docx.txt' }] },
  17: { files: [{ name: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt', slice: ['4.', '6.'] }] },
  18: { files: [{ name: 'NSIGHT_L4_설정_가이드_docx.txt', slice: ['5. GSLB', '6. L4 VIP'] }] },
  19: { files: [{ name: 'NSIGHT_L4_설정_가이드_docx.txt', slice: ['6. L4 VIP', '15. 성능'] }] },
  20: { files: [
    { name: 'NSIGHT_Apache_설정_가이드_docx.txt' },
    { name: '환경셋팅_최종_docx.txt', slice: ['2. WebTopSuite', '3. Tomcat'] },
  ]},
  21: { files: [{ name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['8.', '9.'] }] },
  22: { files: [{ name: 'NSIGHT_Tomcat_설정_가이드_docx.txt' }] },
  23: { files: [{ name: 'NSIGHT_JVM_셋팅_가이드_docx.txt' }] },
  24: { files: [{ name: 'NSIGHT_SpringBoot_설정_가이드_docx.txt' }] },
  25: { files: [
    { name: 'NSIGHT_SpringBoot_설정_가이드_docx.txt', slice: ['5.', '8.'] },
    { name: '아래처럼_SPRING_영역_설정_기준표로_정리하면_됩니다_docx.txt' },
  ]},
  26: { files: [{ name: '2026_06_03_NSIGHT_용량산정_DB_Pool_docx.txt' }] },
  27: { files: [{ name: '환경셋팅_최종_docx.txt', slice: ['6. MyBatis', '7. CruzAPIM'] }] },
  28: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['9. 6단계', '11. DB Connection'] }] },
  29: { files: [
    { name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['9. 세션', '10. Tomcat Cluster'] },
    { name: '환경셋팅_최종_docx.txt', slice: ['4. Spring Session', '5. Hikari'] },
  ]},
  30: { files: [{ name: 'NSIGHT_SpringBoot_설정_가이드_docx.txt', slice: ['6.', '9.'] }] },
  31: { files: [{ name: 'NSIGHT_SpringBoot_설정_가이드_docx.txt', slice: ['10.', '12.'] }] },
  32: { files: [{ name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['10.', '12.'] }] },
  33: { files: [{ name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['13.', '14.'] }] },
  34: { files: [{ name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['14.', '16.'] }] },
  35: { files: [{ name: 'NSIGHT_Apache_설정_가이드_docx.txt', slice: ['7.', '9.'] }] },
  36: { files: [
    { name: '환경셋팅_최종_docx.txt', slice: ['9. 로그', '10. 최종'] },
    { name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['13. 로그', '15. 운영'] },
  ]},
  37: { files: [{ name: '환경셋팅_최종_docx.txt' }] },
  38: { files: [{ name: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt' }] },
  39: { files: [{ name: 'NSIGHT_용량산정_6000지점_세션90분_16CORE128G_정상적용_수정본_확인_docx.txt' }] },
  40: { files: [{ name: 'NSIGHT_32Core_256GB_환경설정_작업가이드_docx.txt' }] },
  41: { files: [
    { name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['17.', '18.'] },
    { name: '환경셋팅_최종_docx.txt', slice: ['7. CruzAPIM', '8. JVM'] },
  ]},
  42: { files: [
    { name: '720_TPS_기준_용량_보고서_docx.txt' },
    { name: '2026_05_24_농협_상호금융_아키텍처_백서_균형_특성_원칙_방법론_docx.txt', slice: ['1.', '3.'] },
  ]},
  43: { files: [{ name: '환경셋팅_최종_docx.txt', slice: ['1. 공통', '10. 최종'] }] },
  44: { files: [{ name: 'NSIGHT_용량산정_검증결과서_docx.txt', slice: ['1.', '3.'] }] },
  45: { files: [
    { name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['7. 4단계', '12. 최종'] },
    { name: '720_TPS_기준_용량_보고서_docx.txt', slice: ['2', '5'] },
  ]},
  46: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['15. 시사점', null] }] },
  47: { files: [
    { name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['16. 성능', '17.'] },
    { name: 'NSIGHT_JVM_셋팅_가이드_docx.txt', slice: ['11. 성능', '12. 장애'] },
    { name: 'NSIGHT_용량산정_검증결과서_docx.txt' },
  ]},
  48: { files: [{ name: 'NSIGHT_용량산정_검증결과서_docx.txt' }] },
  49: { files: [
    { name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['15. 운영', '16.'] },
    { name: 'NSIGHT_JVM_셋팅_가이드_docx.txt', slice: ['10. 모니터링', '11.'] },
  ]},
  50: { files: [
    { name: 'NSIGHT_Timeout_Setting_Guide_docx.txt', slice: ['19. 타임아웃 설정 검증', '20.'] },
    { name: 'NSIGHT_L4_설정_가이드_docx.txt', slice: ['16. 장애', '17.'] },
    { name: 'NSIGHT_OOM_발생원인_진단_해결_가이드_docx.txt' },
  ]},
  51: { files: [{ name: 'NSIGHT_용량산정_검증결과서_docx.txt' }] },
  52: { files: [
    { name: 'NSIGHT_Tomcat_설정_가이드_docx.txt', slice: ['18. 최종', '19.'] },
    { name: 'NSIGHT_JVM_셋팅_가이드_docx.txt', slice: ['13. 최종', '14.'] },
  ]},
  53: { files: [{ name: 'NSIGHT_용량산정_검증결과서_docx.txt' }] },
  54: { files: [{ name: '720_TPS_기준_용량_보고서_docx.txt', slice: ['4.', null] }] },
  55: { files: [{ name: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt', slice: ['7.', null] }] },
  56: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['15. 시사점', null] }] },
  57: { files: [{ name: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt', slice: ['14. 마무리말', null] }] },
};

module.exports.APPENDIX_SOURCES = {
  A: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt',
  B: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt',
  C: 'TPS와_TPMC의_관계_분석_및_실효_처리량_산정_가이드_docx.txt',
  D: 'NSIGHT_8CORE_VM_운영안정성_전략보고서_docx.txt',
  E: '환경셋팅_최종_docx.txt',
  F: '환경셋팅_최종_docx.txt',
  G: 'NSIGHT_Tomcat_설정_가이드_docx.txt',
  H: 'NSIGHT_JVM_셋팅_가이드_docx.txt',
  I: 'NSIGHT_SpringBoot_설정_가이드_docx.txt',
  J: '아래처럼_SPRING_영역_설정_기준표로_정리하면_됩니다_docx.txt',
  K: '2026_06_03_NSIGHT_용량산정_DB_Pool_docx.txt',
  L: '환경셋팅_최종_docx.txt',
  M: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  N: 'NSIGHT_L4_설정_가이드_docx.txt',
  O: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  P: 'NSIGHT_Tomcat_설정_가이드_docx.txt',
  Q: 'NSIGHT_SpringBoot_설정_가이드_docx.txt',
  R: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  S: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  T: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  U: '환경셋팅_최종_docx.txt',
  V: 'NSIGHT_사용자수_동시요청_TPS_AP_DBSession_산정가이드_docx.txt',
  W: '720_TPS_기준_용량_보고서_docx.txt',
  X: 'NSIGHT_Tomcat_설정_가이드_docx.txt',
  Y: 'NSIGHT_Timeout_Setting_Guide_docx.txt',
  Z: 'NSIGHT_용량산정_검증결과서_docx.txt',
  AA: 'NSIGHT_Tomcat_설정_가이드_docx.txt',
  AB: 'NSIGHT_용량산정_검증결과서_docx.txt',
  AC: '2026_05_24_농협_상호금융_아키텍처_백서_균형_특성_원칙_방법론_docx.txt',
  AD: '720_TPS_기준_용량_보고서_docx.txt',
};
