-- Gateway 프록시 거래로그 (Oracle)

CREATE TABLE TCF_GATEWAY_TX_LOG (
    LOG_ID               VARCHAR2(64)  NOT NULL,
    TX_TIME              VARCHAR2(40)  NOT NULL,
    ENV_CODE             VARCHAR2(20),
    BUSINESS_CODE        VARCHAR2(10),
    SERVICE_ID           VARCHAR2(100),
    TRANSACTION_CODE     VARCHAR2(50),
    GUID                 VARCHAR2(64),
    TRACE_ID             VARCHAR2(64),
    USER_ID              VARCHAR2(50),
    BRANCH_ID            VARCHAR2(20),
    SESSION_ID           VARCHAR2(100),
    TARGET_URL           VARCHAR2(500),
    HTTP_STATUS          NUMBER(10),
    RESULT_STATUS        VARCHAR2(20),
    RESULT_CODE          VARCHAR2(20),
    ERROR_CODE           VARCHAR2(50),
    ELAPSED_TIME_MS      NUMBER(19),
    PHASE                VARCHAR2(50),
    CONSTRAINT PK_TCF_GATEWAY_TX_LOG PRIMARY KEY (LOG_ID)
);

CREATE INDEX IX_TCF_GW_TX_01 ON TCF_GATEWAY_TX_LOG (GUID, TX_TIME DESC);
CREATE INDEX IX_TCF_GW_TX_02 ON TCF_GATEWAY_TX_LOG (SERVICE_ID, TX_TIME DESC);
CREATE INDEX IX_TCF_GW_TX_03 ON TCF_GATEWAY_TX_LOG (USER_ID, TX_TIME DESC);
CREATE INDEX IX_TCF_GW_TX_04 ON TCF_GATEWAY_TX_LOG (BUSINESS_CODE, TX_TIME DESC);
