-- Oracle 운영 DDL — tcf-gateway/docs/ROUTING_TABLE.md 참고
-- 시드 데이터는 src/main/resources/data.sql (H2) 와 동일 구조

CREATE TABLE TCF_GATEWAY_ROUTE (
    ROUTE_ID             VARCHAR2(60)  NOT NULL,
    ENV_CODE             VARCHAR2(20)  NOT NULL,
    ROUTE_GROUP_CODE     VARCHAR2(30)  NOT NULL,
    ROUTE_GROUP_NAME     VARCHAR2(100) NOT NULL,
    BUSINESS_CODE        VARCHAR2(10)  NOT NULL,
    BUSINESS_NAME        VARCHAR2(100) NOT NULL,
    TARGET_BASE_URL      VARCHAR2(300) NOT NULL,
    CONTEXT_PATH         VARCHAR2(100) NOT NULL,
    ONLINE_PATH          VARCHAR2(100) DEFAULT '/online' NOT NULL,
    HEALTH_CHECK_PATH    VARCHAR2(200),
    CONNECT_TIMEOUT_MS   NUMBER(10) DEFAULT 3000 NOT NULL,
    READ_TIMEOUT_MS      NUMBER(10) DEFAULT 5000 NOT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y' NOT NULL,
    SORT_ORDER           NUMBER(5),
    DESCRIPTION          VARCHAR2(500),
    CREATED_AT           DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE,
    CONSTRAINT PK_TCF_GATEWAY_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT UK_TCF_GATEWAY_ROUTE_01 UNIQUE (ENV_CODE, BUSINESS_CODE),
    CONSTRAINT CK_TCF_GATEWAY_ROUTE_ENV CHECK (ENV_CODE IN ('LOCAL', 'DEV', 'PRD')),
    CONSTRAINT CK_TCF_GATEWAY_ROUTE_USE CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX IX_TCF_GATEWAY_ROUTE_01 ON TCF_GATEWAY_ROUTE (ENV_CODE, BUSINESS_CODE, USE_YN);
CREATE INDEX IX_TCF_GATEWAY_ROUTE_02 ON TCF_GATEWAY_ROUTE (ENV_CODE, ROUTE_GROUP_CODE, USE_YN);
