-- Oracle 운영 DDL — Gateway 사용자 세션 레지스트리

CREATE TABLE TCF_USER_SESSION (
    SESSION_ID           VARCHAR2(100) NOT NULL,
    USER_ID              VARCHAR2(50)  NOT NULL,
    USER_NAME            VARCHAR2(100),
    BRANCH_ID            VARCHAR2(20),
    CHANNEL_ID           VARCHAR2(20),
    AUTH_GROUP_ID        VARCHAR2(50),
    SESSION_TYPE         VARCHAR2(20)  DEFAULT 'BUSINESS' NOT NULL,
    LOGIN_TIME           TIMESTAMP     NOT NULL,
    LAST_ACCESS_TIME     TIMESTAMP     NOT NULL,
    ABSOLUTE_EXPIRE_TIME TIMESTAMP     NOT NULL,
    CLIENT_IP            VARCHAR2(50),
    USER_AGENT           VARCHAR2(500),
    CENTER_ID            VARCHAR2(20),
    WAS_ID               VARCHAR2(50),
    STATUS               VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    LOGOUT_TIME          TIMESTAMP,
    LOGOUT_REASON        VARCHAR2(200),
    CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_TCF_USER_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT CK_TCF_USER_SESSION_TYPE CHECK (SESSION_TYPE IN ('BUSINESS', 'OM', 'API')),
    CONSTRAINT CK_TCF_USER_SESSION_STATUS CHECK (STATUS IN ('ACTIVE', 'FORCED_LOGOUT', 'EXPIRED', 'LOGGED_OUT'))
);

CREATE INDEX IX_TCF_USER_SESSION_01 ON TCF_USER_SESSION (USER_ID, STATUS);
CREATE INDEX IX_TCF_USER_SESSION_02 ON TCF_USER_SESSION (STATUS, ABSOLUTE_EXPIRE_TIME);
