-- JWT + OM 사용자 원장 (H2 / Oracle 호환)

-- FW 이미지로그 (DefaultFilter / ImageLogHandler)
CREATE TABLE IF NOT EXISTS TB_FW_IMAGE_LOG (
    GUID           VARCHAR(64)   NOT NULL,
    SERVICE_ID     VARCHAR(50),
    SCREEN_ID      VARCHAR(50),
    OPTR_ENO       VARCHAR(20),
    CLIENT_IP      VARCHAR(50),
    REQUEST_TIME   VARCHAR(17),
    RESPONSE_TIME  VARCHAR(17),
    EXCEPTION_TYPE VARCHAR(200),
    EXCEPTION_CODE VARCHAR(50),
    EXCEPTION_MSG  VARCHAR(1000),
    REQUEST_MSG    CLOB,
    RESPONSE_MSG   CLOB,
    CONSTRAINT TB_FW_IMAGE_LOG_PK PRIMARY KEY (GUID)
);

CREATE TABLE IF NOT EXISTS OM_AUTH_GROUP (
    AUTH_GROUP_ID VARCHAR(50) NOT NULL,
    AUTH_GROUP_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (AUTH_GROUP_ID)
);

CREATE TABLE IF NOT EXISTS OM_USER (
    USER_ID VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(200),
    BRANCH_ID VARCHAR(30),
    AUTH_GROUP_ID VARCHAR(50),
    USE_YN CHAR(1) DEFAULT 'Y',
    LAST_LOGIN_TIME VARCHAR(40),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS TCF_JWT_TOKEN (
    TOKEN_ID VARCHAR(64) NOT NULL,
    JTI VARCHAR(100) NOT NULL,
    ISSUER VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    BRANCH_ID VARCHAR(30),
    CHANNEL_ID VARCHAR(30),
    AUTH_GROUP_ID VARCHAR(50),
    TOKEN_TYPE VARCHAR(20) NOT NULL,
    AUDIENCE VARCHAR(100),
    ISSUED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED_YN CHAR(1) DEFAULT 'N',
    REVOKED_AT TIMESTAMP,
    REVOKE_REASON VARCHAR(200),
    CLIENT_IP VARCHAR(50),
    USER_AGENT VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOKEN_ID),
    CONSTRAINT TCF_JWT_TOKEN_UK1 UNIQUE (ISSUER, JTI)
);

CREATE INDEX IF NOT EXISTS IDX_TCF_JWT_TOKEN_USER ON TCF_JWT_TOKEN (USER_ID, EXPIRES_AT);
CREATE INDEX IF NOT EXISTS IDX_TCF_JWT_TOKEN_REVOKED ON TCF_JWT_TOKEN (JTI, ISSUER, REVOKED_YN);

CREATE TABLE IF NOT EXISTS TCF_REFRESH_TOKEN (
    REFRESH_TOKEN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    TOKEN_HASH VARCHAR(256) NOT NULL,
    TOKEN_FAMILY_ID VARCHAR(64),
    ISSUED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    LAST_USED_AT TIMESTAMP,
    ROTATED_YN CHAR(1) DEFAULT 'N',
    REVOKED_YN CHAR(1) DEFAULT 'N',
    REVOKED_AT TIMESTAMP,
    CLIENT_IP VARCHAR(50),
    USER_AGENT VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REFRESH_TOKEN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_TCF_REFRESH_TOKEN_USER ON TCF_REFRESH_TOKEN (USER_ID, EXPIRES_AT);

CREATE TABLE IF NOT EXISTS TCF_TOKEN_DENYLIST (
    ISSUER VARCHAR(100) NOT NULL,
    JTI VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50),
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVOKE_REASON VARCHAR(200),
    PRIMARY KEY (ISSUER, JTI)
);

CREATE INDEX IF NOT EXISTS IDX_TCF_TOKEN_DENYLIST_EXP ON TCF_TOKEN_DENYLIST (EXPIRES_AT);

CREATE TABLE IF NOT EXISTS TCF_JWT_LOGIN_HISTORY (
    LOG_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    LOGIN_RESULT VARCHAR(20) NOT NULL,
    FAIL_REASON VARCHAR(500),
    CHANNEL_ID VARCHAR(30),
    CLIENT_IP VARCHAR(50),
    LOGIN_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (LOG_ID)
);

CREATE INDEX IF NOT EXISTS IDX_TCF_JWT_LOGIN_HIST_USER ON TCF_JWT_LOGIN_HISTORY (USER_ID, LOGIN_TIME);

-- STF 거래통제용 (pdmg-service TB_MG_TX_CONTROL 과 동일 구조). jwt 앱은 기본 비활성.
CREATE TABLE IF NOT EXISTS TB_MG_TX_CONTROL (
    SERVICE_ID       VARCHAR(100)  NOT NULL,
    TRANSACTION_CODE VARCHAR(50)   NOT NULL,
    BUSINESS_CODE    VARCHAR(10)   NOT NULL,
    SERVICE_NAME     VARCHAR(200)  NOT NULL,
    USER_ID          VARCHAR(50)   NOT NULL,
    CHANNEL_ID       VARCHAR(30)   NOT NULL,
    BRANCH_ID        VARCHAR(30)   NOT NULL,
    CONTROL_TYPE     VARCHAR(20)   NOT NULL,
    BLOCK_YN         VARCHAR(1)    NOT NULL,
    CHANGE_REASON    VARCHAR(500),
    REG_USER_ID      VARCHAR(50),
    REG_DTM          VARCHAR(17),
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_MG_TX_CONTROL_PK PRIMARY KEY (
        SERVICE_ID, TRANSACTION_CODE, BUSINESS_CODE, SERVICE_NAME,
        USER_ID, CHANNEL_ID, BRANCH_ID
    )
);
CREATE INDEX IF NOT EXISTS IDX_MG_TX_CTRL_TYPE ON TB_MG_TX_CONTROL (CONTROL_TYPE, BLOCK_YN);

CREATE TABLE IF NOT EXISTS TCF_JWT_SECURITY_POLICY (
    POLICY_ID VARCHAR(20) NOT NULL,
    ISSUER VARCHAR(100) NOT NULL,
    AUDIENCE VARCHAR(100) NOT NULL,
    ACCESS_TOKEN_VALID_MINUTES INT NOT NULL,
    REFRESH_TOKEN_VALID_HOURS INT NOT NULL,
    ALGORITHM VARCHAR(20) NOT NULL,
    CLOCK_SKEW_SECONDS INT NOT NULL,
    DENYLIST_CHECK_ENABLED CHAR(1) DEFAULT 'Y',
    REFRESH_TOKEN_ROTATION_ENABLED CHAR(1) DEFAULT 'Y',
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    PRIMARY KEY (POLICY_ID)
);
