# ============================================================
# NSIGHT SSL 공통 설정
# ============================================================

SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite HIGH:!aNULL:!MD5:!3DES
SSLHonorCipherOrder On
SSLSessionCache shmcb:/app/apache/logs/ssl_scache(512000)
SSLSessionCacheTimeout 300
