# ============================================================
# NSIGHT Reverse Proxy 공통 설정
# ============================================================

ProxyRequests Off
ProxyPreserveHost On
ProxyTimeout 10
ProxyBadHeader IsError
SetEnv proxy-nokeepalive 0

RequestHeader set X-Forwarded-Proto "https" early
RequestHeader set X-Forwarded-Port  "443" early
RequestHeader set X-Forwarded-Host  "nh.marketing.com" early
RequestHeader set X-Real-IP expr=%{REMOTE_ADDR}
