plugins {
    id 'java'
    id 'war'
    id 'eclipse'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'nhnis.mg'
version = '0.0.1-SNAPSHOT'

bootWar {
    enabled = false
}

war {
    enabled = true
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':pdmg-fw')

    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'com.nimbusds:nimbus-jose-jwt:9.37.3'

    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test:6.5.7'

    runtimeOnly 'com.h2database:h2:2.3.232'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

configurations {
    all {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
    configureEach {
        exclude group: 'io.netty', module: 'netty-resolver-dns-native-macos'
        exclude group: 'io.netty', module: 'netty-transport-native-epoll'
        exclude group: 'io.netty', module: 'netty-transport-native-kqueue'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    filteringCharset = 'UTF-8'
}

tasks.named('bootRun').configure {
    jvmArgs = [
            '-Dfile.encoding=UTF-8',
            '-Dsun.jnu.encoding=UTF-8',
            '-Dstdout.encoding=UTF-8',
            '-Dstderr.encoding=UTF-8',
            '-Dconsole.encoding=UTF-8'
    ]
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    jvmArgs '-Dfile.encoding=UTF-8', '-Dsun.jnu.encoding=UTF-8'
}
