CREATE TABLE IF NOT EXISTS EP_USER_EVENT (
    EVENT_ID     VARCHAR(50) PRIMARY KEY,
    USER_ID      VARCHAR(50) NOT NULL,
    EVENT_TYPE   VARCHAR(30) NOT NULL,
    RECEIVED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
