-- OM Operation Management (local H2)

CREATE TABLE IF NOT EXISTS TCF_TX_LOG (
    LOG_ID VARCHAR(64) NOT NULL,
    TX_TIME VARCHAR(40) NOT NULL,
    BUSINESS_CODE VARCHAR(10),
    SERVICE_ID VARCHAR(100),
    TRANSACTION_CODE VARCHAR(50),
    GUID VARCHAR(64) NOT NULL,
    TRACE_ID VARCHAR(64),
    USER_ID VARCHAR(50),
    BRANCH_ID VARCHAR(20),
    RESULT_STATUS VARCHAR(20),
    RESULT_CODE VARCHAR(20),
    ERROR_CODE VARCHAR(50),
    ELAPSED_TIME_MS BIGINT,
    PRIMARY KEY (LOG_ID)
);

CREATE INDEX IF NOT EXISTS IDX_TCF_TX_GUID ON TCF_TX_LOG (GUID, TX_TIME DESC);
CREATE INDEX IF NOT EXISTS IDX_TCF_TX_SVC ON TCF_TX_LOG (SERVICE_ID, TX_TIME DESC);
CREATE INDEX IF NOT EXISTS IDX_TCF_TX_USER ON TCF_TX_LOG (USER_ID, TX_TIME DESC);

CREATE TABLE IF NOT EXISTS TCF_TRANSACTION_CONTROL (
    SERVICE_ID VARCHAR(100) NOT NULL,
    TRANSACTION_CODE VARCHAR(50) NOT NULL,
    BUSINESS_CODE VARCHAR(10) NOT NULL,
    SERVICE_NAME VARCHAR(200) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    CHANNEL_ID VARCHAR(30) NOT NULL,
    BRANCH_ID VARCHAR(30) NOT NULL,
    CONTROL_TYPE VARCHAR(20) NOT NULL DEFAULT 'FULL',
    BLOCK_YN CHAR(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY (
        SERVICE_ID,
        TRANSACTION_CODE,
        BUSINESS_CODE,
        SERVICE_NAME,
        USER_ID,
        CHANNEL_ID,
        BRANCH_ID
    )
);

CREATE INDEX IF NOT EXISTS IDX_TCF_TX_CTRL_USER ON TCF_TRANSACTION_CONTROL (USER_ID, CHANNEL_ID, BRANCH_ID);
CREATE INDEX IF NOT EXISTS IDX_TCF_TX_CTRL_SVC ON TCF_TRANSACTION_CONTROL (BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE);

CREATE TABLE IF NOT EXISTS OM_SERVICE_CATALOG (
    CATALOG_ID VARCHAR(64) NOT NULL,
    BUSINESS_CODE VARCHAR(10) NOT NULL,
    SERVICE_ID VARCHAR(100) NOT NULL,
    TRANSACTION_CODE VARCHAR(50) NOT NULL,
    PROCESSING_TYPE VARCHAR(20) NOT NULL,
    HANDLER_CLASS VARCHAR(200),
    AUTH_CODE VARCHAR(50),
    AUDIT_YN CHAR(1) DEFAULT 'N',
    TIMEOUT_SEC INT DEFAULT 5,
    USE_YN CHAR(1) DEFAULT 'Y',
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY (CATALOG_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_OM_SVC_ID ON OM_SERVICE_CATALOG (SERVICE_ID);

CREATE TABLE IF NOT EXISTS OM_USER (
    USER_ID VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(200),
    BRANCH_ID VARCHAR(20),
    AUTH_GROUP_ID VARCHAR(50),
    USE_YN CHAR(1) DEFAULT 'Y',
    LAST_LOGIN_TIME VARCHAR(40),
    PRIMARY KEY (USER_ID)
);

ALTER TABLE OM_USER ADD COLUMN IF NOT EXISTS PASSWORD_HASH VARCHAR(200);

CREATE TABLE IF NOT EXISTS OM_AUTH_GROUP (
    AUTH_GROUP_ID VARCHAR(50) NOT NULL,
    AUTH_GROUP_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (AUTH_GROUP_ID)
);

CREATE TABLE IF NOT EXISTS OM_MENU (
    MENU_ID VARCHAR(50) NOT NULL,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_URL VARCHAR(200),
    PARENT_MENU_ID VARCHAR(50),
    SORT_ORDER INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (MENU_ID)
);

CREATE TABLE IF NOT EXISTS OM_AUDIT_LOG (
    AUDIT_ID VARCHAR(64) NOT NULL,
    AUDIT_TIME VARCHAR(40) NOT NULL,
    USER_ID VARCHAR(50),
    BRANCH_ID VARCHAR(20),
    CUSTOMER_NO VARCHAR(50),
    FUNCTION_ID VARCHAR(50),
    FUNCTION_NAME VARCHAR(100),
    INQUIRY_REASON VARCHAR(200),
    RESULT_STATUS VARCHAR(20),
    CLIENT_IP VARCHAR(50),
    PRIMARY KEY (AUDIT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_AUDIT_USER ON OM_AUDIT_LOG (USER_ID, AUDIT_TIME DESC);

CREATE TABLE IF NOT EXISTS OM_AP_STATUS (
    AP_ID VARCHAR(50) NOT NULL,
    AP_NAME VARCHAR(100),
    HEALTH_STATUS VARCHAR(20),
    CPU_USAGE_PCT DECIMAL(5,2),
    HEAP_USAGE_PCT DECIMAL(5,2),
    THREAD_COUNT INT,
    CHECKED_AT VARCHAR(40),
    PRIMARY KEY (AP_ID)
);

CREATE TABLE IF NOT EXISTS OM_DB_STATUS (
    DB_ID VARCHAR(50) NOT NULL,
    DB_NAME VARCHAR(100),
    HEALTH_STATUS VARCHAR(20),
    POOL_USAGE_PCT DECIMAL(5,2),
    CHECKED_AT VARCHAR(40),
    PRIMARY KEY (DB_ID)
);

CREATE TABLE IF NOT EXISTS OM_SESSION_STATUS (
    SCOPE_ID VARCHAR(50) NOT NULL,
    SCOPE_NAME VARCHAR(100),
    ACTIVE_COUNT INT,
    EXPIRED_COUNT INT,
    TOTAL_COUNT INT,
    UNIQUE_USER_COUNT INT,
    HEALTH_STATUS VARCHAR(20),
    CHECKED_AT VARCHAR(40),
    PRIMARY KEY (SCOPE_ID)
);

CREATE TABLE IF NOT EXISTS OM_DEPLOY_STATUS (
    BUSINESS_CODE VARCHAR(10) NOT NULL,
    WAR_NAME VARCHAR(50),
    WAR_VERSION VARCHAR(50),
    DEPLOYED_AT VARCHAR(40),
    HEALTH_STATUS VARCHAR(20),
    PRIMARY KEY (BUSINESS_CODE)
);

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OM_ERROR_CODE (
    ERROR_CODE VARCHAR(50) NOT NULL,
    ERROR_CATEGORY VARCHAR(20) NOT NULL,
    USER_MESSAGE VARCHAR(500),
    OPERATOR_MESSAGE VARCHAR(500),
    ACTION_GUIDE VARCHAR(500),
    NOTIFY_TARGET VARCHAR(100),
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (ERROR_CODE)
);

CREATE TABLE IF NOT EXISTS OM_BATCH_JOB (
    JOB_ID VARCHAR(50) NOT NULL,
    JOB_NAME VARCHAR(100) NOT NULL,
    BUSINESS_CODE VARCHAR(10),
    CRON_EXPR VARCHAR(50),
    USE_YN CHAR(1) DEFAULT 'Y',
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY (JOB_ID)
);

CREATE TABLE IF NOT EXISTS OM_BATCH_HISTORY (
    HISTORY_ID VARCHAR(64) NOT NULL,
    JOB_ID VARCHAR(50) NOT NULL,
    RUN_TIME VARCHAR(40) NOT NULL,
    RUN_STATUS VARCHAR(20),
    DURATION_MS BIGINT,
    RESULT_MESSAGE VARCHAR(500),
    PRIMARY KEY (HISTORY_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_BATCH_HIST ON OM_BATCH_HISTORY (JOB_ID, RUN_TIME DESC);

CREATE TABLE IF NOT EXISTS OM_SYSTEM_CONFIG (
    CONFIG_KEY VARCHAR(100) NOT NULL,
    CONFIG_CATEGORY VARCHAR(30) NOT NULL,
    CONFIG_VALUE VARCHAR(500),
    EDITABLE_YN CHAR(1) DEFAULT 'N',
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY (CONFIG_KEY)
);

CREATE TABLE IF NOT EXISTS OM_FILE_DOWNLOAD_LOG (
    LOG_ID VARCHAR(64) NOT NULL,
    DOWNLOAD_TIME VARCHAR(40) NOT NULL,
    USER_ID VARCHAR(50),
    FILE_NAME VARCHAR(200),
    FILE_SIZE BIGINT,
    BUSINESS_CODE VARCHAR(10),
    RESULT_STATUS VARCHAR(20),
    CLIENT_IP VARCHAR(50),
    PRIMARY KEY (LOG_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_FILE_DL_USER ON OM_FILE_DOWNLOAD_LOG (USER_ID, DOWNLOAD_TIME DESC);

CREATE TABLE IF NOT EXISTS UD_FILE_META (
    FILE_ID VARCHAR(36) NOT NULL,
    ORIGINAL_NAME VARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(100),
    FILE_SIZE BIGINT NOT NULL,
    DESCRIPTION VARCHAR(500),
    UPLOAD_USER VARCHAR(50),
    UPLOAD_TIME VARCHAR(40) NOT NULL,
    BUSINESS_CODE VARCHAR(10) DEFAULT 'UD',
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (FILE_ID)
);

CREATE INDEX IF NOT EXISTS UD_FILE_META_IX1 ON UD_FILE_META (UPLOAD_TIME);
CREATE INDEX IF NOT EXISTS UD_FILE_META_IX2 ON UD_FILE_META (UPLOAD_USER);
CREATE INDEX IF NOT EXISTS UD_FILE_META_IX3 ON UD_FILE_META (ORIGINAL_NAME);

CREATE TABLE IF NOT EXISTS OM_COMMON_CODE (
    CODE_GROUP VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    CODE_NAME VARCHAR(100) NOT NULL,
    SORT_ORDER INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y',
    DESCRIPTION VARCHAR(500),
    CREATED_AT VARCHAR(40),
    UPDATED_AT VARCHAR(40),
    PRIMARY KEY (CODE_GROUP, CODE)
);

CREATE TABLE IF NOT EXISTS OM_MESSAGE_STRUCT (
    STRUCT_ID VARCHAR(64) NOT NULL,
    STRUCT_CODE VARCHAR(80) NOT NULL,
    BUSINESS_CODE VARCHAR(10),
    SERVICE_ID VARCHAR(100),
    TRANSACTION_CODE VARCHAR(50),
    MESSAGE_TYPE VARCHAR(20) NOT NULL,
    SEGMENT_TYPE VARCHAR(20) NOT NULL,
    STRUCT_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    SAMPLE_JSON CLOB,
    USE_YN CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (STRUCT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_OM_MSG_STRUCT_CODE ON OM_MESSAGE_STRUCT (STRUCT_CODE);

CREATE TABLE IF NOT EXISTS OM_MESSAGE_FIELD (
    FIELD_ID VARCHAR(64) NOT NULL,
    STRUCT_ID VARCHAR(64) NOT NULL,
    FIELD_KEY VARCHAR(100) NOT NULL,
    FIELD_LABEL VARCHAR(200),
    DATA_TYPE VARCHAR(20) NOT NULL DEFAULT 'STRING',
    REQUIRED_YN CHAR(1) DEFAULT 'N',
    MAX_LENGTH INT,
    DEFAULT_VALUE VARCHAR(500),
    SAMPLE_VALUE VARCHAR(500),
    VALIDATION_RULE VARCHAR(200),
    DESCRIPTION VARCHAR(500),
    SORT_ORDER INT DEFAULT 0,
    PRIMARY KEY (FIELD_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_MSG_FIELD_STRUCT ON OM_MESSAGE_FIELD (STRUCT_ID, SORT_ORDER);

CREATE TABLE IF NOT EXISTS OM_FUNCTION_AUTH (
    AUTH_ID VARCHAR(64) NOT NULL,
    AUTH_GROUP_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(50),
    CAN_INQUIRY CHAR(1) DEFAULT 'N',
    CAN_REGISTER CHAR(1) DEFAULT 'N',
    CAN_UPDATE CHAR(1) DEFAULT 'N',
    CAN_DELETE CHAR(1) DEFAULT 'N',
    CAN_DOWNLOAD CHAR(1) DEFAULT 'N',
    PRIMARY KEY (AUTH_ID)
);

CREATE TABLE IF NOT EXISTS OM_DATA_AUTH (
    AUTH_ID VARCHAR(64) NOT NULL,
    AUTH_GROUP_ID VARCHAR(50) NOT NULL,
    BRANCH_SCOPE VARCHAR(50),
    CUSTOMER_ACCESS_LEVEL VARCHAR(50),
    DESCRIPTION VARCHAR(500),
    PRIMARY KEY (AUTH_ID)
);

CREATE TABLE IF NOT EXISTS OM_AUTH_HISTORY (
    HISTORY_ID VARCHAR(64) NOT NULL,
    CHANGED_AT VARCHAR(40) NOT NULL,
    CHANGED_BY VARCHAR(50),
    TARGET_TYPE VARCHAR(50),
    TARGET_ID VARCHAR(100),
    BEFORE_VALUE VARCHAR(1000),
    AFTER_VALUE VARCHAR(1000),
    CHANGE_REASON VARCHAR(500),
    PRIMARY KEY (HISTORY_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_AUTH_HIST ON OM_AUTH_HISTORY (CHANGED_AT DESC);

CREATE TABLE IF NOT EXISTS OM_CACHE_STATUS (
    CACHE_NAME VARCHAR(100) NOT NULL,
    CACHE_KEY VARCHAR(200) NOT NULL DEFAULT '*',
    ENTRY_COUNT INT DEFAULT 0,
    LAST_UPDATED VARCHAR(40),
    TTL_SEC INT,
    PRIMARY KEY (CACHE_NAME, CACHE_KEY)
);

CREATE TABLE IF NOT EXISTS OM_DEPLOY_REQUEST (
    DEPLOY_REQUEST_ID VARCHAR(40) NOT NULL,
    REQUEST_TYPE VARCHAR(20) NOT NULL,
    ENV_CODE VARCHAR(20),
    BUSINESS_CODE VARCHAR(20),
    MODULE_NAME VARCHAR(100),
    BRANCH_NAME VARCHAR(100),
    COMMIT_ID VARCHAR(100),
    GRADLE_TASK VARCHAR(200),
    ARTIFACT_NAME VARCHAR(200),
    STATUS VARCHAR(30) NOT NULL,
    REQUEST_USER_ID VARCHAR(50),
    APPROVE_USER_ID VARCHAR(50),
    REQUEST_TIME VARCHAR(40) NOT NULL,
    APPROVE_TIME VARCHAR(40),
    START_TIME VARCHAR(40),
    END_TIME VARCHAR(40),
    ERROR_MESSAGE CLOB,
    PRIMARY KEY (DEPLOY_REQUEST_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_DEPLOY_REQ_STATUS ON OM_DEPLOY_REQUEST (STATUS, REQUEST_TIME DESC);
CREATE INDEX IF NOT EXISTS IDX_OM_DEPLOY_REQ_MODULE ON OM_DEPLOY_REQUEST (MODULE_NAME, REQUEST_TIME DESC);

CREATE TABLE IF NOT EXISTS OM_DEPLOY_HISTORY (
    DEPLOY_HISTORY_ID VARCHAR(40) NOT NULL,
    DEPLOY_REQUEST_ID VARCHAR(40),
    ENV_CODE VARCHAR(20),
    TARGET_SERVER VARCHAR(100),
    CONTEXT_PATH VARCHAR(50),
    BEFORE_VERSION VARCHAR(100),
    AFTER_VERSION VARCHAR(100),
    RESULT_CODE VARCHAR(20),
    RESULT_MESSAGE VARCHAR(1000),
    HEALTH_CHECK_URL VARCHAR(500),
    HEALTH_CHECK_RESULT VARCHAR(20),
    CREATED_TIME VARCHAR(40) NOT NULL,
    PRIMARY KEY (DEPLOY_HISTORY_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OM_DEPLOY_HIST_REQ ON OM_DEPLOY_HISTORY (DEPLOY_REQUEST_ID, CREATED_TIME DESC);
