# local - bootRun (port 8082)
server:
  port: 8082

spring:
  application:
    name: nsight-ic-service
  datasource:
    url: jdbc:h2:mem:nsight_ic;MODE=Oracle;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    hikari:
      pool-name: nsight-ic-hikari-local
  h2:
    console:
      enabled: true

nsight:
  integration:
    default-timeout-ms: 3000
    services:
      SV:
        base-url: http://127.0.0.1:8086
        context-path: /sv
        online-path: /online
        connect-timeout-ms: 1000
        read-timeout-ms: 3000
  tcf:
    transaction-log-schema-auto-init: true
    transaction-log-datasource:
      url: jdbc:h2:file:${nsight.txlog.path:./data/nsight-txlog}/nsight_om;MODE=Oracle;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=false
      username: sa
      password:
      driver-class-name: org.h2.Driver