# local - bootRun (port 8097)
server:
  port: 8097

spring:
  application:
    name: nsight-om-service
  datasource:
    url: jdbc:h2:mem:nsight_om;MODE=Oracle;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    hikari:
      pool-name: nsight-om-hikari-local
  h2:
    console:
      enabled: true

nsight:
  tcf:
    transaction-log-schema-auto-init: true
    transaction-log-datasource:
      url: jdbc:h2:file:${nsight.txlog.path:./data/nsight-txlog}/nsight_om;MODE=Oracle;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=false
      username: sa
      password:
      driver-class-name: org.h2.Driver