CREATE TABLE IF NOT EXISTS AV_SAMPLE (
    SAMPLE_KEY   VARCHAR(30) PRIMARY KEY,
    SAMPLE_NAME  VARCHAR(100) NOT NULL,
    USE_YN       CHAR(1) DEFAULT 'Y',
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 조회 검증용 시드 데이터
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-001', 'AV 샘플 첫번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-002', 'AV 샘플 두번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-003', 'AV 샘플 세번째', 'N');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-004', 'AV 샘플 네번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-005', 'AV 샘플 다섯번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-006', 'AV 샘플 여섯번째', 'Y');

-- AV 고객연락처 (C04 확정: 신규 테이블 · PK CONTACT_ID). 운영 SoT 아님, AA 승인 전 운영 DB 반영 금지.
CREATE TABLE IF NOT EXISTS AV_CUSTOMER_CONTACT (
    CONTACT_ID     VARCHAR(30) PRIMARY KEY,
    CUSTOMER_NO    VARCHAR(20) NOT NULL,
    CONTACT_TYPE   VARCHAR(20) NOT NULL,
    CONTACT_VALUE  VARCHAR(200) NOT NULL,
    USE_YN         CHAR(1) DEFAULT 'Y',
    REG_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_AV_CCT_CUST
    ON AV_CUSTOMER_CONTACT (CUSTOMER_NO, USE_YN, CONTACT_TYPE);

MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-001', 'C0001', 'MOBILE', '010-1111-2222', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-002', 'C0001', 'EMAIL', 'c0001@example.com', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-003', 'C0001', 'MOBILE', '010-9999-8888', 'N');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-004', 'C0002', 'MOBILE', '010-3333-4444', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-005', 'C0002', 'HOME', '02-123-4567', 'Y');
