-- LN 시범 스키마 (운영 SoT 아님). AA 승인 전 운영 DB 반영 금지.
CREATE TABLE IF NOT EXISTS LN_CUSTOMER_CONTACT (
    CONTACT_ID     VARCHAR(30) PRIMARY KEY,
    CUSTOMER_NO    VARCHAR(20) NOT NULL,
    CONTACT_TYPE   VARCHAR(20) NOT NULL,
    CONTACT_VALUE  VARCHAR(200) NOT NULL,
    USE_YN         CHAR(1) DEFAULT 'Y',
    REG_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_LN_CCT_CUST
    ON LN_CUSTOMER_CONTACT (CUSTOMER_NO, USE_YN, CONTACT_TYPE);

-- 시범 시드
MERGE INTO LN_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('CCT-001', 'C0001', 'MOBILE', '010-1111-2222', 'Y');
MERGE INTO LN_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('CCT-002', 'C0001', 'EMAIL', 'c0001@example.com', 'Y');
MERGE INTO LN_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('CCT-003', 'C0001', 'MOBILE', '010-9999-8888', 'N');
MERGE INTO LN_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('CCT-004', 'C0002', 'MOBILE', '010-3333-4444', 'Y');
MERGE INTO LN_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('CCT-005', 'C0002', 'HOME', '02-123-4567', 'Y');
